// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: communication.proto

package communication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientID) Reset() {
	*x = ClientID{}
	mi := &file_communication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientID) ProtoMessage() {}

func (x *ClientID) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientID.ProtoReflect.Descriptor instead.
func (*ClientID) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{0}
}

func (x *ClientID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_communication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Memory        float64                `protobuf:"fixed64,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Cpu           float64                `protobuf:"fixed64,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_communication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{2}
}

func (x *ServerStatus) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ServerStatus) GetMemory() float64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *ServerStatus) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

type IsWhitelistedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Whitelisted   bool                   `protobuf:"varint,1,opt,name=whitelisted,proto3" json:"whitelisted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsWhitelistedResponse) Reset() {
	*x = IsWhitelistedResponse{}
	mi := &file_communication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsWhitelistedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsWhitelistedResponse) ProtoMessage() {}

func (x *IsWhitelistedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsWhitelistedResponse.ProtoReflect.Descriptor instead.
func (*IsWhitelistedResponse) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{3}
}

func (x *IsWhitelistedResponse) GetWhitelisted() bool {
	if x != nil {
		return x.Whitelisted
	}
	return false
}

type ServerDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SatelliteName string                 `protobuf:"bytes,1,opt,name=satelliteName,proto3" json:"satelliteName,omitempty"`
	TestPhase     string                 `protobuf:"bytes,2,opt,name=testPhase,proto3" json:"testPhase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerDetails) Reset() {
	*x = ServerDetails{}
	mi := &file_communication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerDetails) ProtoMessage() {}

func (x *ServerDetails) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerDetails.ProtoReflect.Descriptor instead.
func (*ServerDetails) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{4}
}

func (x *ServerDetails) GetSatelliteName() string {
	if x != nil {
		return x.SatelliteName
	}
	return ""
}

func (x *ServerDetails) GetTestPhase() string {
	if x != nil {
		return x.TestPhase
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_communication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{5}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_communication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{6}
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type AcqDASMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AcqMode       string                 `protobuf:"bytes,1,opt,name=acqMode,proto3" json:"acqMode,omitempty"`
	DasDetails    []*AcqDasDetails       `protobuf:"bytes,2,rep,name=dasDetails,proto3" json:"dasDetails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcqDASMap) Reset() {
	*x = AcqDASMap{}
	mi := &file_communication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcqDASMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcqDASMap) ProtoMessage() {}

func (x *AcqDASMap) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcqDASMap.ProtoReflect.Descriptor instead.
func (*AcqDASMap) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{7}
}

func (x *AcqDASMap) GetAcqMode() string {
	if x != nil {
		return x.AcqMode
	}
	return ""
}

func (x *AcqDASMap) GetDasDetails() []*AcqDasDetails {
	if x != nil {
		return x.DasDetails
	}
	return nil
}

type AcqDasDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DasName       string                 `protobuf:"bytes,1,opt,name=dasName,proto3" json:"dasName,omitempty"`
	DpuNumber     int32                  `protobuf:"varint,2,opt,name=dpuNumber,proto3" json:"dpuNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcqDasDetails) Reset() {
	*x = AcqDasDetails{}
	mi := &file_communication_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcqDasDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcqDasDetails) ProtoMessage() {}

func (x *AcqDasDetails) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcqDasDetails.ProtoReflect.Descriptor instead.
func (*AcqDasDetails) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{8}
}

func (x *AcqDasDetails) GetDasName() string {
	if x != nil {
		return x.DasName
	}
	return ""
}

func (x *AcqDasDetails) GetDpuNumber() int32 {
	if x != nil {
		return x.DpuNumber
	}
	return 0
}

type DASStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DasStatus     []*DASStatusResponse   `protobuf:"bytes,1,rep,name=dasStatus,proto3" json:"dasStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DASStatus) Reset() {
	*x = DASStatus{}
	mi := &file_communication_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DASStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DASStatus) ProtoMessage() {}

func (x *DASStatus) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DASStatus.ProtoReflect.Descriptor instead.
func (*DASStatus) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{9}
}

func (x *DASStatus) GetDasStatus() []*DASStatusResponse {
	if x != nil {
		return x.DasStatus
	}
	return nil
}

type DASStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DasName       string                 `protobuf:"bytes,1,opt,name=dasName,proto3" json:"dasName,omitempty"`
	DpuNumber     int32                  `protobuf:"varint,2,opt,name=dpuNumber,proto3" json:"dpuNumber,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Alarm         bool                   `protobuf:"varint,4,opt,name=alarm,proto3" json:"alarm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DASStatusResponse) Reset() {
	*x = DASStatusResponse{}
	mi := &file_communication_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DASStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DASStatusResponse) ProtoMessage() {}

func (x *DASStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DASStatusResponse.ProtoReflect.Descriptor instead.
func (*DASStatusResponse) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{10}
}

func (x *DASStatusResponse) GetDasName() string {
	if x != nil {
		return x.DasName
	}
	return ""
}

func (x *DASStatusResponse) GetDpuNumber() int32 {
	if x != nil {
		return x.DpuNumber
	}
	return 0
}

func (x *DASStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DASStatusResponse) GetAlarm() bool {
	if x != nil {
		return x.Alarm
	}
	return false
}

type DASStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AcqMode       string                 `protobuf:"bytes,2,opt,name=acqMode,proto3" json:"acqMode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DASStatusRequest) Reset() {
	*x = DASStatusRequest{}
	mi := &file_communication_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DASStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DASStatusRequest) ProtoMessage() {}

func (x *DASStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DASStatusRequest.ProtoReflect.Descriptor instead.
func (*DASStatusRequest) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{11}
}

func (x *DASStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DASStatusRequest) GetAcqMode() string {
	if x != nil {
		return x.AcqMode
	}
	return ""
}

type AcquisitionParameters struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AcqModes       []string               `protobuf:"bytes,1,rep,name=acqModes,proto3" json:"acqModes,omitempty"`
	Payloads       []string               `protobuf:"bytes,2,rep,name=payloads,proto3" json:"payloads,omitempty"`
	ConfigNames    []string               `protobuf:"bytes,3,rep,name=configNames,proto3" json:"configNames,omitempty"`
	AcqTypes       []string               `protobuf:"bytes,4,rep,name=acqTypes,proto3" json:"acqTypes,omitempty"`
	ResultProfiles []string               `protobuf:"bytes,5,rep,name=resultProfiles,proto3" json:"resultProfiles,omitempty"`
	DasMap         []*AcqDASMap           `protobuf:"bytes,6,rep,name=dasMap,proto3" json:"dasMap,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcquisitionParameters) Reset() {
	*x = AcquisitionParameters{}
	mi := &file_communication_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquisitionParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquisitionParameters) ProtoMessage() {}

func (x *AcquisitionParameters) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquisitionParameters.ProtoReflect.Descriptor instead.
func (*AcquisitionParameters) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{12}
}

func (x *AcquisitionParameters) GetAcqModes() []string {
	if x != nil {
		return x.AcqModes
	}
	return nil
}

func (x *AcquisitionParameters) GetPayloads() []string {
	if x != nil {
		return x.Payloads
	}
	return nil
}

func (x *AcquisitionParameters) GetConfigNames() []string {
	if x != nil {
		return x.ConfigNames
	}
	return nil
}

func (x *AcquisitionParameters) GetAcqTypes() []string {
	if x != nil {
		return x.AcqTypes
	}
	return nil
}

func (x *AcquisitionParameters) GetResultProfiles() []string {
	if x != nil {
		return x.ResultProfiles
	}
	return nil
}

func (x *AcquisitionParameters) GetDasMap() []*AcqDASMap {
	if x != nil {
		return x.DasMap
	}
	return nil
}

type FileAcquisitionParameters struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FrameTypes     []string               `protobuf:"bytes,1,rep,name=frameTypes,proto3" json:"frameTypes,omitempty"`
	AcqModes       []string               `protobuf:"bytes,2,rep,name=acqModes,proto3" json:"acqModes,omitempty"`
	Payloads       []string               `protobuf:"bytes,3,rep,name=payloads,proto3" json:"payloads,omitempty"`
	ConfigNames    []string               `protobuf:"bytes,4,rep,name=configNames,proto3" json:"configNames,omitempty"`
	ResultProfiles []string               `protobuf:"bytes,5,rep,name=resultProfiles,proto3" json:"resultProfiles,omitempty"`
	FrameTypeMap   []*FrameTypeMap        `protobuf:"bytes,6,rep,name=frameTypeMap,proto3" json:"frameTypeMap,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileAcquisitionParameters) Reset() {
	*x = FileAcquisitionParameters{}
	mi := &file_communication_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileAcquisitionParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAcquisitionParameters) ProtoMessage() {}

func (x *FileAcquisitionParameters) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAcquisitionParameters.ProtoReflect.Descriptor instead.
func (*FileAcquisitionParameters) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{13}
}

func (x *FileAcquisitionParameters) GetFrameTypes() []string {
	if x != nil {
		return x.FrameTypes
	}
	return nil
}

func (x *FileAcquisitionParameters) GetAcqModes() []string {
	if x != nil {
		return x.AcqModes
	}
	return nil
}

func (x *FileAcquisitionParameters) GetPayloads() []string {
	if x != nil {
		return x.Payloads
	}
	return nil
}

func (x *FileAcquisitionParameters) GetConfigNames() []string {
	if x != nil {
		return x.ConfigNames
	}
	return nil
}

func (x *FileAcquisitionParameters) GetResultProfiles() []string {
	if x != nil {
		return x.ResultProfiles
	}
	return nil
}

func (x *FileAcquisitionParameters) GetFrameTypeMap() []*FrameTypeMap {
	if x != nil {
		return x.FrameTypeMap
	}
	return nil
}

type FrameTypeMap struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FrameType        string                 `protobuf:"bytes,1,opt,name=frameType,proto3" json:"frameType,omitempty"`
	FrameIdentifiers []string               `protobuf:"bytes,2,rep,name=frameIdentifiers,proto3" json:"frameIdentifiers,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FrameTypeMap) Reset() {
	*x = FrameTypeMap{}
	mi := &file_communication_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameTypeMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameTypeMap) ProtoMessage() {}

func (x *FrameTypeMap) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameTypeMap.ProtoReflect.Descriptor instead.
func (*FrameTypeMap) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{14}
}

func (x *FrameTypeMap) GetFrameType() string {
	if x != nil {
		return x.FrameType
	}
	return ""
}

func (x *FrameTypeMap) GetFrameIdentifiers() []string {
	if x != nil {
		return x.FrameIdentifiers
	}
	return nil
}

type TestPhases struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestPhases    []string               `protobuf:"bytes,1,rep,name=testPhases,proto3" json:"testPhases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestPhases) Reset() {
	*x = TestPhases{}
	mi := &file_communication_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPhases) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPhases) ProtoMessage() {}

func (x *TestPhases) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPhases.ProtoReflect.Descriptor instead.
func (*TestPhases) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{15}
}

func (x *TestPhases) GetTestPhases() []string {
	if x != nil {
		return x.TestPhases
	}
	return nil
}

type TestPhaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TestPhase     string                 `protobuf:"bytes,2,opt,name=testPhase,proto3" json:"testPhase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestPhaseRequest) Reset() {
	*x = TestPhaseRequest{}
	mi := &file_communication_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPhaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPhaseRequest) ProtoMessage() {}

func (x *TestPhaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPhaseRequest.ProtoReflect.Descriptor instead.
func (*TestPhaseRequest) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{16}
}

func (x *TestPhaseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestPhaseRequest) GetTestPhase() string {
	if x != nil {
		return x.TestPhase
	}
	return ""
}

type DASIPAddresses struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DasIPAddresses []*DASIPAddress        `protobuf:"bytes,1,rep,name=dasIPAddresses,proto3" json:"dasIPAddresses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DASIPAddresses) Reset() {
	*x = DASIPAddresses{}
	mi := &file_communication_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DASIPAddresses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DASIPAddresses) ProtoMessage() {}

func (x *DASIPAddresses) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DASIPAddresses.ProtoReflect.Descriptor instead.
func (*DASIPAddresses) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{17}
}

func (x *DASIPAddresses) GetDasIPAddresses() []*DASIPAddress {
	if x != nil {
		return x.DasIPAddresses
	}
	return nil
}

type DASIPAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DASIPAddress) Reset() {
	*x = DASIPAddress{}
	mi := &file_communication_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DASIPAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DASIPAddress) ProtoMessage() {}

func (x *DASIPAddress) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DASIPAddress.ProtoReflect.Descriptor instead.
func (*DASIPAddress) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{18}
}

func (x *DASIPAddress) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DASIPAddress) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type AcqRemark struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Time          string                 `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcqRemark) Reset() {
	*x = AcqRemark{}
	mi := &file_communication_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcqRemark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcqRemark) ProtoMessage() {}

func (x *AcqRemark) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcqRemark.ProtoReflect.Descriptor instead.
func (*AcqRemark) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{19}
}

func (x *AcqRemark) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *AcqRemark) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *AcqRemark) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type AcqRemarks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AcqRemarks    []*AcqRemark           `protobuf:"bytes,1,rep,name=acqRemarks,proto3" json:"acqRemarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcqRemarks) Reset() {
	*x = AcqRemarks{}
	mi := &file_communication_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcqRemarks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcqRemarks) ProtoMessage() {}

func (x *AcqRemarks) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcqRemarks.ProtoReflect.Descriptor instead.
func (*AcqRemarks) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{20}
}

func (x *AcqRemarks) GetAcqRemarks() []*AcqRemark {
	if x != nil {
		return x.AcqRemarks
	}
	return nil
}

var File_communication_proto protoreflect.FileDescriptor

const file_communication_proto_rawDesc = "" +
	"\n" +
	"\x13communication.proto\x12\rCommunication\"\x1a\n" +
	"\bClientID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"V\n" +
	"\fServerStatus\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\x01R\x06memory\x12\x10\n" +
	"\x03cpu\x18\x03 \x01(\x01R\x03cpu\"9\n" +
	"\x15IsWhitelistedResponse\x12 \n" +
	"\vwhitelisted\x18\x01 \x01(\bR\vwhitelisted\"S\n" +
	"\rServerDetails\x12$\n" +
	"\rsatelliteName\x18\x01 \x01(\tR\rsatelliteName\x12\x1c\n" +
	"\ttestPhase\x18\x02 \x01(\tR\ttestPhase\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"K\n" +
	"\rLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\"c\n" +
	"\tAcqDASMap\x12\x18\n" +
	"\aacqMode\x18\x01 \x01(\tR\aacqMode\x12<\n" +
	"\n" +
	"dasDetails\x18\x02 \x03(\v2\x1c.Communication.AcqDasDetailsR\n" +
	"dasDetails\"G\n" +
	"\rAcqDasDetails\x12\x18\n" +
	"\adasName\x18\x01 \x01(\tR\adasName\x12\x1c\n" +
	"\tdpuNumber\x18\x02 \x01(\x05R\tdpuNumber\"K\n" +
	"\tDASStatus\x12>\n" +
	"\tdasStatus\x18\x01 \x03(\v2 .Communication.DASStatusResponseR\tdasStatus\"y\n" +
	"\x11DASStatusResponse\x12\x18\n" +
	"\adasName\x18\x01 \x01(\tR\adasName\x12\x1c\n" +
	"\tdpuNumber\x18\x02 \x01(\x05R\tdpuNumber\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05alarm\x18\x04 \x01(\bR\x05alarm\"<\n" +
	"\x10DASStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aacqMode\x18\x02 \x01(\tR\aacqMode\"\xe7\x01\n" +
	"\x15AcquisitionParameters\x12\x1a\n" +
	"\bacqModes\x18\x01 \x03(\tR\bacqModes\x12\x1a\n" +
	"\bpayloads\x18\x02 \x03(\tR\bpayloads\x12 \n" +
	"\vconfigNames\x18\x03 \x03(\tR\vconfigNames\x12\x1a\n" +
	"\bacqTypes\x18\x04 \x03(\tR\bacqTypes\x12&\n" +
	"\x0eresultProfiles\x18\x05 \x03(\tR\x0eresultProfiles\x120\n" +
	"\x06dasMap\x18\x06 \x03(\v2\x18.Communication.AcqDASMapR\x06dasMap\"\xfe\x01\n" +
	"\x19FileAcquisitionParameters\x12\x1e\n" +
	"\n" +
	"frameTypes\x18\x01 \x03(\tR\n" +
	"frameTypes\x12\x1a\n" +
	"\bacqModes\x18\x02 \x03(\tR\bacqModes\x12\x1a\n" +
	"\bpayloads\x18\x03 \x03(\tR\bpayloads\x12 \n" +
	"\vconfigNames\x18\x04 \x03(\tR\vconfigNames\x12&\n" +
	"\x0eresultProfiles\x18\x05 \x03(\tR\x0eresultProfiles\x12?\n" +
	"\fframeTypeMap\x18\x06 \x03(\v2\x1b.Communication.FrameTypeMapR\fframeTypeMap\"X\n" +
	"\fFrameTypeMap\x12\x1c\n" +
	"\tframeType\x18\x01 \x01(\tR\tframeType\x12*\n" +
	"\x10frameIdentifiers\x18\x02 \x03(\tR\x10frameIdentifiers\",\n" +
	"\n" +
	"TestPhases\x12\x1e\n" +
	"\n" +
	"testPhases\x18\x01 \x03(\tR\n" +
	"testPhases\"@\n" +
	"\x10TestPhaseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttestPhase\x18\x02 \x01(\tR\ttestPhase\"U\n" +
	"\x0eDASIPAddresses\x12C\n" +
	"\x0edasIPAddresses\x18\x01 \x03(\v2\x1b.Communication.DASIPAddressR\x0edasIPAddresses\"@\n" +
	"\fDASIPAddress\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tipAddress\x18\x02 \x01(\tR\tipAddress\"K\n" +
	"\tAcqRemark\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x12\n" +
	"\x04time\x18\x02 \x01(\tR\x04time\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\"F\n" +
	"\n" +
	"AcqRemarks\x128\n" +
	"\n" +
	"acqRemarks\x18\x01 \x03(\v2\x18.Communication.AcqRemarkR\n" +
	"acqRemarks2\xb3\b\n" +
	"\rCommunication\x12I\n" +
	"\x0fGetServerStatus\x12\x17.Communication.ClientID\x1a\x1b.Communication.ServerStatus0\x01\x12N\n" +
	"\rIsWhitelisted\x12\x17.Communication.ClientID\x1a$.Communication.IsWhitelistedResponse\x12I\n" +
	"\x10GetServerDetails\x12\x17.Communication.ClientID\x1a\x1c.Communication.ServerDetails\x12B\n" +
	"\x05Login\x12\x1b.Communication.LoginRequest\x1a\x1c.Communication.LoginResponse\x12Y\n" +
	"\x18GetAcquisitionParameters\x12\x17.Communication.ClientID\x1a$.Communication.AcquisitionParameters\x12K\n" +
	"\fGetDASStatus\x12\x1f.Communication.DASStatusRequest\x1a\x18.Communication.DASStatus0\x01\x12a\n" +
	"\x1cGetFileAcquisitionParameters\x12\x17.Communication.ClientID\x1a(.Communication.FileAcquisitionParameters\x12F\n" +
	"\x10GetAllTestPhases\x12\x17.Communication.ClientID\x1a\x19.Communication.TestPhases\x12C\n" +
	"\fAddTestPhase\x12\x1f.Communication.TestPhaseRequest\x1a\x12.Communication.Ack\x12F\n" +
	"\x0fSelectTestPhase\x12\x1f.Communication.TestPhaseRequest\x1a\x12.Communication.Ack\x12K\n" +
	"\x11GetDASIPAddresses\x12\x17.Communication.ClientID\x1a\x1d.Communication.DASIPAddresses\x12E\n" +
	"\x12ChangeDASIPAddress\x12\x1b.Communication.DASIPAddress\x1a\x12.Communication.Ack\x12C\n" +
	"\rGetAcqRemarks\x12\x17.Communication.ClientID\x1a\x19.Communication.AcqRemarks\x12?\n" +
	"\x0fChangeAcqRemark\x12\x18.Communication.AcqRemark\x1a\x12.Communication.AckB\x1cZ\x1acsrsp/server/communicationb\x06proto3"

var (
	file_communication_proto_rawDescOnce sync.Once
	file_communication_proto_rawDescData []byte
)

func file_communication_proto_rawDescGZIP() []byte {
	file_communication_proto_rawDescOnce.Do(func() {
		file_communication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_communication_proto_rawDesc), len(file_communication_proto_rawDesc)))
	})
	return file_communication_proto_rawDescData
}

var file_communication_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_communication_proto_goTypes = []any{
	(*ClientID)(nil),                  // 0: Communication.ClientID
	(*Ack)(nil),                       // 1: Communication.Ack
	(*ServerStatus)(nil),              // 2: Communication.ServerStatus
	(*IsWhitelistedResponse)(nil),     // 3: Communication.IsWhitelistedResponse
	(*ServerDetails)(nil),             // 4: Communication.ServerDetails
	(*LoginRequest)(nil),              // 5: Communication.LoginRequest
	(*LoginResponse)(nil),             // 6: Communication.LoginResponse
	(*AcqDASMap)(nil),                 // 7: Communication.AcqDASMap
	(*AcqDasDetails)(nil),             // 8: Communication.AcqDasDetails
	(*DASStatus)(nil),                 // 9: Communication.DASStatus
	(*DASStatusResponse)(nil),         // 10: Communication.DASStatusResponse
	(*DASStatusRequest)(nil),          // 11: Communication.DASStatusRequest
	(*AcquisitionParameters)(nil),     // 12: Communication.AcquisitionParameters
	(*FileAcquisitionParameters)(nil), // 13: Communication.FileAcquisitionParameters
	(*FrameTypeMap)(nil),              // 14: Communication.FrameTypeMap
	(*TestPhases)(nil),                // 15: Communication.TestPhases
	(*TestPhaseRequest)(nil),          // 16: Communication.TestPhaseRequest
	(*DASIPAddresses)(nil),            // 17: Communication.DASIPAddresses
	(*DASIPAddress)(nil),              // 18: Communication.DASIPAddress
	(*AcqRemark)(nil),                 // 19: Communication.AcqRemark
	(*AcqRemarks)(nil),                // 20: Communication.AcqRemarks
}
var file_communication_proto_depIdxs = []int32{
	8,  // 0: Communication.AcqDASMap.dasDetails:type_name -> Communication.AcqDasDetails
	10, // 1: Communication.DASStatus.dasStatus:type_name -> Communication.DASStatusResponse
	7,  // 2: Communication.AcquisitionParameters.dasMap:type_name -> Communication.AcqDASMap
	14, // 3: Communication.FileAcquisitionParameters.frameTypeMap:type_name -> Communication.FrameTypeMap
	18, // 4: Communication.DASIPAddresses.dasIPAddresses:type_name -> Communication.DASIPAddress
	19, // 5: Communication.AcqRemarks.acqRemarks:type_name -> Communication.AcqRemark
	0,  // 6: Communication.Communication.GetServerStatus:input_type -> Communication.ClientID
	0,  // 7: Communication.Communication.IsWhitelisted:input_type -> Communication.ClientID
	0,  // 8: Communication.Communication.GetServerDetails:input_type -> Communication.ClientID
	5,  // 9: Communication.Communication.Login:input_type -> Communication.LoginRequest
	0,  // 10: Communication.Communication.GetAcquisitionParameters:input_type -> Communication.ClientID
	11, // 11: Communication.Communication.GetDASStatus:input_type -> Communication.DASStatusRequest
	0,  // 12: Communication.Communication.GetFileAcquisitionParameters:input_type -> Communication.ClientID
	0,  // 13: Communication.Communication.GetAllTestPhases:input_type -> Communication.ClientID
	16, // 14: Communication.Communication.AddTestPhase:input_type -> Communication.TestPhaseRequest
	16, // 15: Communication.Communication.SelectTestPhase:input_type -> Communication.TestPhaseRequest
	0,  // 16: Communication.Communication.GetDASIPAddresses:input_type -> Communication.ClientID
	18, // 17: Communication.Communication.ChangeDASIPAddress:input_type -> Communication.DASIPAddress
	0,  // 18: Communication.Communication.GetAcqRemarks:input_type -> Communication.ClientID
	19, // 19: Communication.Communication.ChangeAcqRemark:input_type -> Communication.AcqRemark
	2,  // 20: Communication.Communication.GetServerStatus:output_type -> Communication.ServerStatus
	3,  // 21: Communication.Communication.IsWhitelisted:output_type -> Communication.IsWhitelistedResponse
	4,  // 22: Communication.Communication.GetServerDetails:output_type -> Communication.ServerDetails
	6,  // 23: Communication.Communication.Login:output_type -> Communication.LoginResponse
	12, // 24: Communication.Communication.GetAcquisitionParameters:output_type -> Communication.AcquisitionParameters
	9,  // 25: Communication.Communication.GetDASStatus:output_type -> Communication.DASStatus
	13, // 26: Communication.Communication.GetFileAcquisitionParameters:output_type -> Communication.FileAcquisitionParameters
	15, // 27: Communication.Communication.GetAllTestPhases:output_type -> Communication.TestPhases
	1,  // 28: Communication.Communication.AddTestPhase:output_type -> Communication.Ack
	1,  // 29: Communication.Communication.SelectTestPhase:output_type -> Communication.Ack
	17, // 30: Communication.Communication.GetDASIPAddresses:output_type -> Communication.DASIPAddresses
	1,  // 31: Communication.Communication.ChangeDASIPAddress:output_type -> Communication.Ack
	20, // 32: Communication.Communication.GetAcqRemarks:output_type -> Communication.AcqRemarks
	1,  // 33: Communication.Communication.ChangeAcqRemark:output_type -> Communication.Ack
	20, // [20:34] is the sub-list for method output_type
	6,  // [6:20] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_communication_proto_init() }
func file_communication_proto_init() {
	if File_communication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_communication_proto_rawDesc), len(file_communication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_communication_proto_goTypes,
		DependencyIndexes: file_communication_proto_depIdxs,
		MessageInfos:      file_communication_proto_msgTypes,
	}.Build()
	File_communication_proto = out.File
	file_communication_proto_goTypes = nil
	file_communication_proto_depIdxs = nil
}
