// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: communication.proto

package communication

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Communication_GetServerStatus_FullMethodName = "/Communication.Communication/GetServerStatus"
	Communication_IsWhitelisted_FullMethodName   = "/Communication.Communication/IsWhitelisted"
)

// CommunicationClient is the client API for Communication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommunicationClient interface {
	GetServerStatus(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerStatus], error)
	IsWhitelisted(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*IsWhitelistedResponse, error)
}

type communicationClient struct {
	cc grpc.ClientConnInterface
}

func NewCommunicationClient(cc grpc.ClientConnInterface) CommunicationClient {
	return &communicationClient{cc}
}

func (c *communicationClient) GetServerStatus(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Communication_ServiceDesc.Streams[0], Communication_GetServerStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientID, ServerStatus]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Communication_GetServerStatusClient = grpc.ServerStreamingClient[ServerStatus]

func (c *communicationClient) IsWhitelisted(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*IsWhitelistedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsWhitelistedResponse)
	err := c.cc.Invoke(ctx, Communication_IsWhitelisted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommunicationServer is the server API for Communication service.
// All implementations must embed UnimplementedCommunicationServer
// for forward compatibility.
type CommunicationServer interface {
	GetServerStatus(*ClientID, grpc.ServerStreamingServer[ServerStatus]) error
	IsWhitelisted(context.Context, *ClientID) (*IsWhitelistedResponse, error)
	mustEmbedUnimplementedCommunicationServer()
}

// UnimplementedCommunicationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommunicationServer struct{}

func (UnimplementedCommunicationServer) GetServerStatus(*ClientID, grpc.ServerStreamingServer[ServerStatus]) error {
	return status.Error(codes.Unimplemented, "method GetServerStatus not implemented")
}
func (UnimplementedCommunicationServer) IsWhitelisted(context.Context, *ClientID) (*IsWhitelistedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsWhitelisted not implemented")
}
func (UnimplementedCommunicationServer) mustEmbedUnimplementedCommunicationServer() {}
func (UnimplementedCommunicationServer) testEmbeddedByValue()                       {}

// UnsafeCommunicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommunicationServer will
// result in compilation errors.
type UnsafeCommunicationServer interface {
	mustEmbedUnimplementedCommunicationServer()
}

func RegisterCommunicationServer(s grpc.ServiceRegistrar, srv CommunicationServer) {
	// If the following call panics, it indicates UnimplementedCommunicationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Communication_ServiceDesc, srv)
}

func _Communication_GetServerStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommunicationServer).GetServerStatus(m, &grpc.GenericServerStream[ClientID, ServerStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Communication_GetServerStatusServer = grpc.ServerStreamingServer[ServerStatus]

func _Communication_IsWhitelisted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServer).IsWhitelisted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Communication_IsWhitelisted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServer).IsWhitelisted(ctx, req.(*ClientID))
	}
	return interceptor(ctx, in, info, handler)
}

// Communication_ServiceDesc is the grpc.ServiceDesc for Communication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Communication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Communication.Communication",
	HandlerType: (*CommunicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsWhitelisted",
			Handler:    _Communication_IsWhitelisted_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetServerStatus",
			Handler:       _Communication_GetServerStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "communication.proto",
}
