// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: communication.proto

package communication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientID) Reset() {
	*x = ClientID{}
	mi := &file_communication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientID) ProtoMessage() {}

func (x *ClientID) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientID.ProtoReflect.Descriptor instead.
func (*ClientID) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{0}
}

func (x *ClientID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ServerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Memory        float64                `protobuf:"fixed64,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Cpu           float64                `protobuf:"fixed64,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_communication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{1}
}

func (x *ServerStatus) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ServerStatus) GetMemory() float64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *ServerStatus) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

type IsWhitelistedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Whitelisted   bool                   `protobuf:"varint,1,opt,name=whitelisted,proto3" json:"whitelisted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsWhitelistedResponse) Reset() {
	*x = IsWhitelistedResponse{}
	mi := &file_communication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsWhitelistedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsWhitelistedResponse) ProtoMessage() {}

func (x *IsWhitelistedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsWhitelistedResponse.ProtoReflect.Descriptor instead.
func (*IsWhitelistedResponse) Descriptor() ([]byte, []int) {
	return file_communication_proto_rawDescGZIP(), []int{2}
}

func (x *IsWhitelistedResponse) GetWhitelisted() bool {
	if x != nil {
		return x.Whitelisted
	}
	return false
}

var File_communication_proto protoreflect.FileDescriptor

const file_communication_proto_rawDesc = "" +
	"\n" +
	"\x13communication.proto\x12\rCommunication\"\x1a\n" +
	"\bClientID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"V\n" +
	"\fServerStatus\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\x01R\x06memory\x12\x10\n" +
	"\x03cpu\x18\x03 \x01(\x01R\x03cpu\"9\n" +
	"\x15IsWhitelistedResponse\x12 \n" +
	"\vwhitelisted\x18\x01 \x01(\bR\vwhitelisted2\xaa\x01\n" +
	"\rCommunication\x12I\n" +
	"\x0fGetServerStatus\x12\x17.Communication.ClientID\x1a\x1b.Communication.ServerStatus0\x01\x12N\n" +
	"\rIsWhitelisted\x12\x17.Communication.ClientID\x1a$.Communication.IsWhitelistedResponseB\x1cZ\x1acsrsp/server/communicationb\x06proto3"

var (
	file_communication_proto_rawDescOnce sync.Once
	file_communication_proto_rawDescData []byte
)

func file_communication_proto_rawDescGZIP() []byte {
	file_communication_proto_rawDescOnce.Do(func() {
		file_communication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_communication_proto_rawDesc), len(file_communication_proto_rawDesc)))
	})
	return file_communication_proto_rawDescData
}

var file_communication_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_communication_proto_goTypes = []any{
	(*ClientID)(nil),              // 0: Communication.ClientID
	(*ServerStatus)(nil),          // 1: Communication.ServerStatus
	(*IsWhitelistedResponse)(nil), // 2: Communication.IsWhitelistedResponse
}
var file_communication_proto_depIdxs = []int32{
	0, // 0: Communication.Communication.GetServerStatus:input_type -> Communication.ClientID
	0, // 1: Communication.Communication.IsWhitelisted:input_type -> Communication.ClientID
	1, // 2: Communication.Communication.GetServerStatus:output_type -> Communication.ServerStatus
	2, // 3: Communication.Communication.IsWhitelisted:output_type -> Communication.IsWhitelistedResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_communication_proto_init() }
func file_communication_proto_init() {
	if File_communication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_communication_proto_rawDesc), len(file_communication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_communication_proto_goTypes,
		DependencyIndexes: file_communication_proto_depIdxs,
		MessageInfos:      file_communication_proto_msgTypes,
	}.Build()
	File_communication_proto = out.File
	file_communication_proto_goTypes = nil
	file_communication_proto_depIdxs = nil
}
