// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: communication.proto

package communication

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Communication_GetServerStatus_FullMethodName              = "/Communication.Communication/GetServerStatus"
	Communication_IsWhitelisted_FullMethodName                = "/Communication.Communication/IsWhitelisted"
	Communication_GetServerDetails_FullMethodName             = "/Communication.Communication/GetServerDetails"
	Communication_Login_FullMethodName                        = "/Communication.Communication/Login"
	Communication_GetAcquisitionParameters_FullMethodName     = "/Communication.Communication/GetAcquisitionParameters"
	Communication_GetDASStatus_FullMethodName                 = "/Communication.Communication/GetDASStatus"
	Communication_GetFileAcquisitionParameters_FullMethodName = "/Communication.Communication/GetFileAcquisitionParameters"
	Communication_GetAllTestPhases_FullMethodName             = "/Communication.Communication/GetAllTestPhases"
	Communication_AddTestPhase_FullMethodName                 = "/Communication.Communication/AddTestPhase"
	Communication_SelectTestPhase_FullMethodName              = "/Communication.Communication/SelectTestPhase"
	Communication_GetDASIPAddresses_FullMethodName            = "/Communication.Communication/GetDASIPAddresses"
	Communication_ChangeDASIPAddress_FullMethodName           = "/Communication.Communication/ChangeDASIPAddress"
	Communication_GetAcqRemarks_FullMethodName                = "/Communication.Communication/GetAcqRemarks"
	Communication_ChangeAcqRemark_FullMethodName              = "/Communication.Communication/ChangeAcqRemark"
	Communication_GetDeveloperOptions_FullMethodName          = "/Communication.Communication/GetDeveloperOptions"
	Communication_SetDeveloperOptions_FullMethodName          = "/Communication.Communication/SetDeveloperOptions"
)

// CommunicationClient is the client API for Communication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommunicationClient interface {
	GetServerStatus(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerStatus], error)
	IsWhitelisted(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*IsWhitelistedResponse, error)
	GetServerDetails(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*ServerDetails, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	GetAcquisitionParameters(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*AcquisitionParameters, error)
	GetDASStatus(ctx context.Context, in *DASStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DASStatus], error)
	GetFileAcquisitionParameters(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*FileAcquisitionParameters, error)
	GetAllTestPhases(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*TestPhases, error)
	AddTestPhase(ctx context.Context, in *TestPhaseRequest, opts ...grpc.CallOption) (*Ack, error)
	SelectTestPhase(ctx context.Context, in *TestPhaseRequest, opts ...grpc.CallOption) (*Ack, error)
	GetDASIPAddresses(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*DASIPAddresses, error)
	ChangeDASIPAddress(ctx context.Context, in *DASIPAddress, opts ...grpc.CallOption) (*Ack, error)
	GetAcqRemarks(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*AcqRemarks, error)
	ChangeAcqRemark(ctx context.Context, in *AcqRemark, opts ...grpc.CallOption) (*Ack, error)
	GetDeveloperOptions(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*DeveloperOptions, error)
	SetDeveloperOptions(ctx context.Context, in *DeveloperOptions, opts ...grpc.CallOption) (*Ack, error)
}

type communicationClient struct {
	cc grpc.ClientConnInterface
}

func NewCommunicationClient(cc grpc.ClientConnInterface) CommunicationClient {
	return &communicationClient{cc}
}

func (c *communicationClient) GetServerStatus(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Communication_ServiceDesc.Streams[0], Communication_GetServerStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientID, ServerStatus]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Communication_GetServerStatusClient = grpc.ServerStreamingClient[ServerStatus]

func (c *communicationClient) IsWhitelisted(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*IsWhitelistedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsWhitelistedResponse)
	err := c.cc.Invoke(ctx, Communication_IsWhitelisted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationClient) GetServerDetails(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*ServerDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerDetails)
	err := c.cc.Invoke(ctx, Communication_GetServerDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, Communication_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationClient) GetAcquisitionParameters(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*AcquisitionParameters, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquisitionParameters)
	err := c.cc.Invoke(ctx, Communication_GetAcquisitionParameters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationClient) GetDASStatus(ctx context.Context, in *DASStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DASStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Communication_ServiceDesc.Streams[1], Communication_GetDASStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DASStatusRequest, DASStatus]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Communication_GetDASStatusClient = grpc.ServerStreamingClient[DASStatus]

func (c *communicationClient) GetFileAcquisitionParameters(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*FileAcquisitionParameters, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileAcquisitionParameters)
	err := c.cc.Invoke(ctx, Communication_GetFileAcquisitionParameters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationClient) GetAllTestPhases(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*TestPhases, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestPhases)
	err := c.cc.Invoke(ctx, Communication_GetAllTestPhases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationClient) AddTestPhase(ctx context.Context, in *TestPhaseRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, Communication_AddTestPhase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationClient) SelectTestPhase(ctx context.Context, in *TestPhaseRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, Communication_SelectTestPhase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationClient) GetDASIPAddresses(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*DASIPAddresses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DASIPAddresses)
	err := c.cc.Invoke(ctx, Communication_GetDASIPAddresses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationClient) ChangeDASIPAddress(ctx context.Context, in *DASIPAddress, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, Communication_ChangeDASIPAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationClient) GetAcqRemarks(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*AcqRemarks, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcqRemarks)
	err := c.cc.Invoke(ctx, Communication_GetAcqRemarks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationClient) ChangeAcqRemark(ctx context.Context, in *AcqRemark, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, Communication_ChangeAcqRemark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationClient) GetDeveloperOptions(ctx context.Context, in *ClientID, opts ...grpc.CallOption) (*DeveloperOptions, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeveloperOptions)
	err := c.cc.Invoke(ctx, Communication_GetDeveloperOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communicationClient) SetDeveloperOptions(ctx context.Context, in *DeveloperOptions, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, Communication_SetDeveloperOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommunicationServer is the server API for Communication service.
// All implementations must embed UnimplementedCommunicationServer
// for forward compatibility.
type CommunicationServer interface {
	GetServerStatus(*ClientID, grpc.ServerStreamingServer[ServerStatus]) error
	IsWhitelisted(context.Context, *ClientID) (*IsWhitelistedResponse, error)
	GetServerDetails(context.Context, *ClientID) (*ServerDetails, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	GetAcquisitionParameters(context.Context, *ClientID) (*AcquisitionParameters, error)
	GetDASStatus(*DASStatusRequest, grpc.ServerStreamingServer[DASStatus]) error
	GetFileAcquisitionParameters(context.Context, *ClientID) (*FileAcquisitionParameters, error)
	GetAllTestPhases(context.Context, *ClientID) (*TestPhases, error)
	AddTestPhase(context.Context, *TestPhaseRequest) (*Ack, error)
	SelectTestPhase(context.Context, *TestPhaseRequest) (*Ack, error)
	GetDASIPAddresses(context.Context, *ClientID) (*DASIPAddresses, error)
	ChangeDASIPAddress(context.Context, *DASIPAddress) (*Ack, error)
	GetAcqRemarks(context.Context, *ClientID) (*AcqRemarks, error)
	ChangeAcqRemark(context.Context, *AcqRemark) (*Ack, error)
	GetDeveloperOptions(context.Context, *ClientID) (*DeveloperOptions, error)
	SetDeveloperOptions(context.Context, *DeveloperOptions) (*Ack, error)
	mustEmbedUnimplementedCommunicationServer()
}

// UnimplementedCommunicationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommunicationServer struct{}

func (UnimplementedCommunicationServer) GetServerStatus(*ClientID, grpc.ServerStreamingServer[ServerStatus]) error {
	return status.Error(codes.Unimplemented, "method GetServerStatus not implemented")
}
func (UnimplementedCommunicationServer) IsWhitelisted(context.Context, *ClientID) (*IsWhitelistedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsWhitelisted not implemented")
}
func (UnimplementedCommunicationServer) GetServerDetails(context.Context, *ClientID) (*ServerDetails, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerDetails not implemented")
}
func (UnimplementedCommunicationServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedCommunicationServer) GetAcquisitionParameters(context.Context, *ClientID) (*AcquisitionParameters, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAcquisitionParameters not implemented")
}
func (UnimplementedCommunicationServer) GetDASStatus(*DASStatusRequest, grpc.ServerStreamingServer[DASStatus]) error {
	return status.Error(codes.Unimplemented, "method GetDASStatus not implemented")
}
func (UnimplementedCommunicationServer) GetFileAcquisitionParameters(context.Context, *ClientID) (*FileAcquisitionParameters, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileAcquisitionParameters not implemented")
}
func (UnimplementedCommunicationServer) GetAllTestPhases(context.Context, *ClientID) (*TestPhases, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllTestPhases not implemented")
}
func (UnimplementedCommunicationServer) AddTestPhase(context.Context, *TestPhaseRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTestPhase not implemented")
}
func (UnimplementedCommunicationServer) SelectTestPhase(context.Context, *TestPhaseRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SelectTestPhase not implemented")
}
func (UnimplementedCommunicationServer) GetDASIPAddresses(context.Context, *ClientID) (*DASIPAddresses, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDASIPAddresses not implemented")
}
func (UnimplementedCommunicationServer) ChangeDASIPAddress(context.Context, *DASIPAddress) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeDASIPAddress not implemented")
}
func (UnimplementedCommunicationServer) GetAcqRemarks(context.Context, *ClientID) (*AcqRemarks, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAcqRemarks not implemented")
}
func (UnimplementedCommunicationServer) ChangeAcqRemark(context.Context, *AcqRemark) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeAcqRemark not implemented")
}
func (UnimplementedCommunicationServer) GetDeveloperOptions(context.Context, *ClientID) (*DeveloperOptions, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeveloperOptions not implemented")
}
func (UnimplementedCommunicationServer) SetDeveloperOptions(context.Context, *DeveloperOptions) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDeveloperOptions not implemented")
}
func (UnimplementedCommunicationServer) mustEmbedUnimplementedCommunicationServer() {}
func (UnimplementedCommunicationServer) testEmbeddedByValue()                       {}

// UnsafeCommunicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommunicationServer will
// result in compilation errors.
type UnsafeCommunicationServer interface {
	mustEmbedUnimplementedCommunicationServer()
}

func RegisterCommunicationServer(s grpc.ServiceRegistrar, srv CommunicationServer) {
	// If the following call panics, it indicates UnimplementedCommunicationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Communication_ServiceDesc, srv)
}

func _Communication_GetServerStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommunicationServer).GetServerStatus(m, &grpc.GenericServerStream[ClientID, ServerStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Communication_GetServerStatusServer = grpc.ServerStreamingServer[ServerStatus]

func _Communication_IsWhitelisted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServer).IsWhitelisted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Communication_IsWhitelisted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServer).IsWhitelisted(ctx, req.(*ClientID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Communication_GetServerDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServer).GetServerDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Communication_GetServerDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServer).GetServerDetails(ctx, req.(*ClientID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Communication_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Communication_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Communication_GetAcquisitionParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServer).GetAcquisitionParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Communication_GetAcquisitionParameters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServer).GetAcquisitionParameters(ctx, req.(*ClientID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Communication_GetDASStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DASStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommunicationServer).GetDASStatus(m, &grpc.GenericServerStream[DASStatusRequest, DASStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Communication_GetDASStatusServer = grpc.ServerStreamingServer[DASStatus]

func _Communication_GetFileAcquisitionParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServer).GetFileAcquisitionParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Communication_GetFileAcquisitionParameters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServer).GetFileAcquisitionParameters(ctx, req.(*ClientID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Communication_GetAllTestPhases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServer).GetAllTestPhases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Communication_GetAllTestPhases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServer).GetAllTestPhases(ctx, req.(*ClientID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Communication_AddTestPhase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestPhaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServer).AddTestPhase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Communication_AddTestPhase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServer).AddTestPhase(ctx, req.(*TestPhaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Communication_SelectTestPhase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestPhaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServer).SelectTestPhase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Communication_SelectTestPhase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServer).SelectTestPhase(ctx, req.(*TestPhaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Communication_GetDASIPAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServer).GetDASIPAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Communication_GetDASIPAddresses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServer).GetDASIPAddresses(ctx, req.(*ClientID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Communication_ChangeDASIPAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DASIPAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServer).ChangeDASIPAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Communication_ChangeDASIPAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServer).ChangeDASIPAddress(ctx, req.(*DASIPAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Communication_GetAcqRemarks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServer).GetAcqRemarks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Communication_GetAcqRemarks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServer).GetAcqRemarks(ctx, req.(*ClientID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Communication_ChangeAcqRemark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcqRemark)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServer).ChangeAcqRemark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Communication_ChangeAcqRemark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServer).ChangeAcqRemark(ctx, req.(*AcqRemark))
	}
	return interceptor(ctx, in, info, handler)
}

func _Communication_GetDeveloperOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServer).GetDeveloperOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Communication_GetDeveloperOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServer).GetDeveloperOptions(ctx, req.(*ClientID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Communication_SetDeveloperOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeveloperOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunicationServer).SetDeveloperOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Communication_SetDeveloperOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunicationServer).SetDeveloperOptions(ctx, req.(*DeveloperOptions))
	}
	return interceptor(ctx, in, info, handler)
}

// Communication_ServiceDesc is the grpc.ServiceDesc for Communication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Communication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Communication.Communication",
	HandlerType: (*CommunicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsWhitelisted",
			Handler:    _Communication_IsWhitelisted_Handler,
		},
		{
			MethodName: "GetServerDetails",
			Handler:    _Communication_GetServerDetails_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Communication_Login_Handler,
		},
		{
			MethodName: "GetAcquisitionParameters",
			Handler:    _Communication_GetAcquisitionParameters_Handler,
		},
		{
			MethodName: "GetFileAcquisitionParameters",
			Handler:    _Communication_GetFileAcquisitionParameters_Handler,
		},
		{
			MethodName: "GetAllTestPhases",
			Handler:    _Communication_GetAllTestPhases_Handler,
		},
		{
			MethodName: "AddTestPhase",
			Handler:    _Communication_AddTestPhase_Handler,
		},
		{
			MethodName: "SelectTestPhase",
			Handler:    _Communication_SelectTestPhase_Handler,
		},
		{
			MethodName: "GetDASIPAddresses",
			Handler:    _Communication_GetDASIPAddresses_Handler,
		},
		{
			MethodName: "ChangeDASIPAddress",
			Handler:    _Communication_ChangeDASIPAddress_Handler,
		},
		{
			MethodName: "GetAcqRemarks",
			Handler:    _Communication_GetAcqRemarks_Handler,
		},
		{
			MethodName: "ChangeAcqRemark",
			Handler:    _Communication_ChangeAcqRemark_Handler,
		},
		{
			MethodName: "GetDeveloperOptions",
			Handler:    _Communication_GetDeveloperOptions_Handler,
		},
		{
			MethodName: "SetDeveloperOptions",
			Handler:    _Communication_SetDeveloperOptions_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetServerStatus",
			Handler:       _Communication_GetServerStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetDASStatus",
			Handler:       _Communication_GetDASStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "communication.proto",
}
