syntax = "proto3";

package Communication;

option go_package = "csrsp/server/communication";

message ClientID{
    string id = 1;
}

message Ack{
    bool ok = 1;
    string message = 2;
}

message ServerStatus {
    string timestamp = 1;
    double memory = 2;
    double cpu = 3;
}

message IsWhitelistedResponse {
    bool whitelisted = 1;
}

message ServerDetails {
    string satelliteName = 1;
    string testPhase = 2;
}

message LoginRequest {
    string username = 1;
    string password = 2;
}

message LoginResponse {
    bool success = 1;
    repeated string permissions = 2;
}

message AcqDASMap{
    string acqMode = 1;
    repeated AcqDasDetails dasDetails = 2;
}

message AcqDasDetails{
    string dasName = 1;
    int32 dpuNumber = 2;
}

message DASStatus{
    repeated DASStatusResponse dasStatus = 1;
}

message DASStatusResponse{
    string dasName = 1;
    int32 dpuNumber = 2;
    string status = 3;
    bool alarm = 4;
}

message DASStatusRequest{
    string id = 1;
    string acqMode = 2;
}


message AcquisitionParameters{
    repeated string acqModes = 1;
    repeated string payloads = 2;
    repeated string configNames = 3;
    repeated string acqTypes = 4;
    repeated string resultProfiles = 5;
    repeated AcqDASMap dasMap = 6;
}

message FileAcquisitionParameters{
    repeated string frameTypes = 1;
    repeated string acqModes = 2;
    repeated string payloads = 3;
    repeated string configNames = 4;
    repeated string resultProfiles = 5;
    repeated FrameTypeMap frameTypeMap = 6;
}

message FrameTypeMap{
    string frameType = 1;
    repeated string frameIdentifiers = 2;
}

message TestPhases{
    repeated string testPhases = 1;
}

message TestPhaseRequest{
    string id = 1;
    string testPhase = 2;
}

message DASIPAddresses{
    repeated DASIPAddress dasIPAddresses = 1;
}

message DASIPAddress{
    string name = 1;
    string ipAddress = 2;
}

message AcqRemark{
    string phase = 1;
    string acqMode = 2;
    string config = 3;
    string date = 4;
    string time = 5;
    string remark = 6;
}

message AcqRemarks{
    repeated AcqRemark acqRemarks = 1;
}

message DeveloperOptions{
    bool autoArchival = 1;
    bool enableParallelProcessing = 2;
    string encryptionMode = 3;
    string logLevel = 4;
    int32 endProcessID = 5;
    int32 maxThreads = 6;
    int32 bufferLength = 7;
}


service Communication{
    rpc GetServerStatus (ClientID) returns (stream ServerStatus);
    rpc IsWhitelisted(ClientID) returns (IsWhitelistedResponse);
    rpc GetServerDetails(ClientID) returns (ServerDetails);
    rpc Login(LoginRequest) returns (LoginResponse);
    rpc GetAcquisitionParameters(ClientID) returns (AcquisitionParameters);
    rpc GetDASStatus(DASStatusRequest) returns (stream DASStatus);
    rpc GetFileAcquisitionParameters(ClientID) returns (FileAcquisitionParameters);
    rpc GetAllTestPhases(ClientID) returns (TestPhases);
    rpc AddTestPhase(TestPhaseRequest) returns (Ack);
    rpc SelectTestPhase(TestPhaseRequest) returns (Ack);
    rpc GetDASIPAddresses(ClientID) returns (DASIPAddresses);
    rpc ChangeDASIPAddress(DASIPAddress) returns (Ack);
    rpc GetAcqRemarks(ClientID) returns (AcqRemarks);
    rpc ChangeAcqRemark(AcqRemark) returns (Ack);
    rpc GetDeveloperOptions(ClientID) returns (DeveloperOptions);
    rpc SetDeveloperOptions(DeveloperOptions) returns (Ack);
}
