// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

type AcquisitionmodeAcqtype string

const (
	AcquisitionmodeAcqtypeAcquisition AcquisitionmodeAcqtype = "Acquisition"
	AcquisitionmodeAcqtypeBER         AcquisitionmodeAcqtype = "BER"
)

func (e *AcquisitionmodeAcqtype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AcquisitionmodeAcqtype(s)
	case string:
		*e = AcquisitionmodeAcqtype(s)
	default:
		return fmt.Errorf("unsupported scan type for AcquisitionmodeAcqtype: %T", src)
	}
	return nil
}

type NullAcquisitionmodeAcqtype struct {
	AcquisitionmodeAcqtype AcquisitionmodeAcqtype
	Valid                  bool // Valid is true if AcquisitionmodeAcqtype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAcquisitionmodeAcqtype) Scan(value interface{}) error {
	if value == nil {
		ns.AcquisitionmodeAcqtype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AcquisitionmodeAcqtype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAcquisitionmodeAcqtype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AcquisitionmodeAcqtype), nil
}

type AnalogtypeDatatype string

const (
	AnalogtypeDatatypeInt32        AnalogtypeDatatype = "int_32"
	AnalogtypeDatatypeInt64        AnalogtypeDatatype = "int_64"
	AnalogtypeDatatypeFloatIeee32  AnalogtypeDatatype = "float_ieee_32"
	AnalogtypeDatatypeFloatIeee64  AnalogtypeDatatype = "float_ieee_64"
	AnalogtypeDatatypeFloat1750a32 AnalogtypeDatatype = "float_1750a_32"
	AnalogtypeDatatypeFloat1750a48 AnalogtypeDatatype = "float_1750a_48"
	AnalogtypeDatatypeInt16        AnalogtypeDatatype = "int_16"
	AnalogtypeDatatypeUint16       AnalogtypeDatatype = "uint_16"
	AnalogtypeDatatypeUint32       AnalogtypeDatatype = "uint_32"
	AnalogtypeDatatypeUint64       AnalogtypeDatatype = "uint_64"
)

func (e *AnalogtypeDatatype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnalogtypeDatatype(s)
	case string:
		*e = AnalogtypeDatatype(s)
	default:
		return fmt.Errorf("unsupported scan type for AnalogtypeDatatype: %T", src)
	}
	return nil
}

type NullAnalogtypeDatatype struct {
	AnalogtypeDatatype AnalogtypeDatatype
	Valid              bool // Valid is true if AnalogtypeDatatype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnalogtypeDatatype) Scan(value interface{}) error {
	if value == nil {
		ns.AnalogtypeDatatype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnalogtypeDatatype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnalogtypeDatatype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnalogtypeDatatype), nil
}

type DasdetailsDastype string

const (
	DasdetailsDastypeHDR  DasdetailsDastype = "HDR"
	DasdetailsDastypePDPS DasdetailsDastype = "PDPS"
	DasdetailsDastypeTTCP DasdetailsDastype = "TTCP"
	DasdetailsDastypeCDP  DasdetailsDastype = "CDP"
)

func (e *DasdetailsDastype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DasdetailsDastype(s)
	case string:
		*e = DasdetailsDastype(s)
	default:
		return fmt.Errorf("unsupported scan type for DasdetailsDastype: %T", src)
	}
	return nil
}

type NullDasdetailsDastype struct {
	DasdetailsDastype DasdetailsDastype
	Valid             bool // Valid is true if DasdetailsDastype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDasdetailsDastype) Scan(value interface{}) error {
	if value == nil {
		ns.DasdetailsDastype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DasdetailsDastype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDasdetailsDastype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DasdetailsDastype), nil
}

type FrametypesProcessedoracquired string

const (
	FrametypesProcessedoracquiredProcessed FrametypesProcessedoracquired = "Processed"
	FrametypesProcessedoracquiredAcquired  FrametypesProcessedoracquired = "Acquired"
)

func (e *FrametypesProcessedoracquired) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FrametypesProcessedoracquired(s)
	case string:
		*e = FrametypesProcessedoracquired(s)
	default:
		return fmt.Errorf("unsupported scan type for FrametypesProcessedoracquired: %T", src)
	}
	return nil
}

type NullFrametypesProcessedoracquired struct {
	FrametypesProcessedoracquired FrametypesProcessedoracquired
	Valid                         bool // Valid is true if FrametypesProcessedoracquired is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFrametypesProcessedoracquired) Scan(value interface{}) error {
	if value == nil {
		ns.FrametypesProcessedoracquired, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FrametypesProcessedoracquired.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFrametypesProcessedoracquired) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FrametypesProcessedoracquired), nil
}

type FrametypesType string

const (
	FrametypesTypeAux       FrametypesType = "Aux"
	FrametypesTypeOptical   FrametypesType = "Optical"
	FrametypesTypeNone      FrametypesType = "None"
	FrametypesTypeLBT       FrametypesType = "LBT"
	FrametypesTypeImage     FrametypesType = "Image"
	FrametypesTypeRS        FrametypesType = "RS"
	FrametypesTypeMicrowave FrametypesType = "Microwave"
)

func (e *FrametypesType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FrametypesType(s)
	case string:
		*e = FrametypesType(s)
	default:
		return fmt.Errorf("unsupported scan type for FrametypesType: %T", src)
	}
	return nil
}

type NullFrametypesType struct {
	FrametypesType FrametypesType
	Valid          bool // Valid is true if FrametypesType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFrametypesType) Scan(value interface{}) error {
	if value == nil {
		ns.FrametypesType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FrametypesType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFrametypesType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FrametypesType), nil
}

type ParameterdetailsParametertype string

const (
	ParameterdetailsParametertypeRadix     ParameterdetailsParametertype = "Radix"
	ParameterdetailsParametertypeFSC       ParameterdetailsParametertype = "FSC"
	ParameterdetailsParametertypeStatus    ParameterdetailsParametertype = "Status"
	ParameterdetailsParametertypeAnalog    ParameterdetailsParametertype = "Analog"
	ParameterdetailsParametertypeIncrement ParameterdetailsParametertype = "Increment"
	ParameterdetailsParametertypeCRC       ParameterdetailsParametertype = "CRC"
)

func (e *ParameterdetailsParametertype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ParameterdetailsParametertype(s)
	case string:
		*e = ParameterdetailsParametertype(s)
	default:
		return fmt.Errorf("unsupported scan type for ParameterdetailsParametertype: %T", src)
	}
	return nil
}

type NullParameterdetailsParametertype struct {
	ParameterdetailsParametertype ParameterdetailsParametertype
	Valid                         bool // Valid is true if ParameterdetailsParametertype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullParameterdetailsParametertype) Scan(value interface{}) error {
	if value == nil {
		ns.ParameterdetailsParametertype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ParameterdetailsParametertype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullParameterdetailsParametertype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ParameterdetailsParametertype), nil
}

type RemoteparametersDatatype string

const (
	RemoteparametersDatatypeString RemoteparametersDatatype = "string"
	RemoteparametersDatatypeInt    RemoteparametersDatatype = "int"
)

func (e *RemoteparametersDatatype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RemoteparametersDatatype(s)
	case string:
		*e = RemoteparametersDatatype(s)
	default:
		return fmt.Errorf("unsupported scan type for RemoteparametersDatatype: %T", src)
	}
	return nil
}

type NullRemoteparametersDatatype struct {
	RemoteparametersDatatype RemoteparametersDatatype
	Valid                    bool // Valid is true if RemoteparametersDatatype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRemoteparametersDatatype) Scan(value interface{}) error {
	if value == nil {
		ns.RemoteparametersDatatype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RemoteparametersDatatype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRemoteparametersDatatype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RemoteparametersDatatype), nil
}

type VideosubframesPixelaccesstype string

const (
	VideosubframesPixelaccesstypeOdd    VideosubframesPixelaccesstype = "Odd"
	VideosubframesPixelaccesstypeEven   VideosubframesPixelaccesstype = "Even"
	VideosubframesPixelaccesstypeAll    VideosubframesPixelaccesstype = "All"
	VideosubframesPixelaccesstypeValue3 VideosubframesPixelaccesstype = ""
)

func (e *VideosubframesPixelaccesstype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VideosubframesPixelaccesstype(s)
	case string:
		*e = VideosubframesPixelaccesstype(s)
	default:
		return fmt.Errorf("unsupported scan type for VideosubframesPixelaccesstype: %T", src)
	}
	return nil
}

type NullVideosubframesPixelaccesstype struct {
	VideosubframesPixelaccesstype VideosubframesPixelaccesstype
	Valid                         bool // Valid is true if VideosubframesPixelaccesstype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVideosubframesPixelaccesstype) Scan(value interface{}) error {
	if value == nil {
		ns.VideosubframesPixelaccesstype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VideosubframesPixelaccesstype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVideosubframesPixelaccesstype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VideosubframesPixelaccesstype), nil
}

type VideosubframesSubframetype string

const (
	VideosubframesSubframetypeBand   VideosubframesSubframetype = "Band"
	VideosubframesSubframetypePort   VideosubframesSubframetype = "Port"
	VideosubframesSubframetypeValue2 VideosubframesSubframetype = ""
	VideosubframesSubframetypeValue3 VideosubframesSubframetype = ""
)

func (e *VideosubframesSubframetype) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VideosubframesSubframetype(s)
	case string:
		*e = VideosubframesSubframetype(s)
	default:
		return fmt.Errorf("unsupported scan type for VideosubframesSubframetype: %T", src)
	}
	return nil
}

type NullVideosubframesSubframetype struct {
	VideosubframesSubframetype VideosubframesSubframetype
	Valid                      bool // Valid is true if VideosubframesSubframetype is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVideosubframesSubframetype) Scan(value interface{}) error {
	if value == nil {
		ns.VideosubframesSubframetype, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VideosubframesSubframetype.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVideosubframesSubframetype) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VideosubframesSubframetype), nil
}

type Acquisition struct {
	Acquisitionid int32
	Systemname    string
	Satname       string
	Testphase     string
	Acqmode       string
	Date          string
	Time          string
	Configname    string
	Remark        string
}

type Acquisitionmode struct {
	Acqid   int32
	Satname string
	Acqmode string
	Acqtype AcquisitionmodeAcqtype
}

type Analogtype struct {
	Paramid                      string
	Equation                     string
	Datatype                     AnalogtypeDatatype
	Variablename                 string
	Parameterids                 sql.NullString
	Valuevalidationrequired      bool
	Differencevalidationrequired bool
	Lowerlimitvalue              sql.NullFloat64
	Upperlimitvalue              sql.NullFloat64
	Tolerancevalue               sql.NullFloat64
	Differencevalue              sql.NullFloat64
	Differencetolerance          sql.NullFloat64
}

type Berlogging struct {
	Berid         int32
	Acqmode       string
	Dasid         int32
	Componentcode int32
	Frameid       int32
}

type Bitdetail struct {
	Bitid     int32
	Paramid   string
	Wordno    int32
	Validbits string
}

type Configuration struct {
	Configid   int32
	Satname    string
	Acqmode    string
	Configname string
	Logic      string
}

type Consolidatedreport struct {
	Consolidatedreportid int32
	Acquisitionid        int32
	Systemname           string
	Frametype            string
	Frameid              sql.NullString
	Auxdatacorrect       sql.NullString
	Maxmean              sql.NullFloat64
	Meanofmean           sql.NullFloat64
	Maxsd                sql.NullFloat64
	Meansd               sql.NullFloat64
	Rmssd                sql.NullFloat64
	Path                 sql.NullString
	Noofframes           string
}

type Crctype struct {
	Paramid       string
	Startword     int32
	Noofwords     int32
	Crcpolynomial sql.NullString
}

type Dascomponentdetail struct {
	Componentid         int32
	Componentname       string
	Parentcompname      sql.NullString
	Componentcode       string
	Totallengthinwords  int32
	Configlengthinwords int32
	Excludedwords       sql.NullString
	Startword           int32
	Startbit            int32
	Noofbits            int32
	Value               int32
	Enabled             bool
}

type Dasconfiguration struct {
	ID               int32
	Acquisitionmode  string
	Dasid            int32
	Componentcode    string
	Setparameters    json.RawMessage
	Verifyparameters json.RawMessage
	Executionorder   int32
	Delayafterms     int32
}

type Dasdetail struct {
	Dasid     int32
	Dasname   string
	Dastype   DasdetailsDastype
	Ipaddress string
	Timeout   int32
}

type Daspath struct {
	Daspathid      int32
	Acqmode        string
	Chainnumber    int32
	Dasid          int32
	Dpunumber      int32
	Dataframeid    int32
	Headerframeid  int32
	Trailerframeid int32
}

type Datadownloadpermission struct {
	Userid  int32
	Frameid int32
}

type Frame struct {
	Frameid          int32
	Frametype        string
	Frameidentifier  string
	Framefilename    string
	Framelength      int32
	Identifyingvalue sql.NullInt32
}

type Frametype struct {
	Frametypeid          int32
	Satname              string
	Frametype            string
	Type                 FrametypesType
	Processedoracquired  FrametypesProcessedoracquired
	Tobewritten          bool
	Tobearchived         bool
	Identifyingparam     string
	Framelengthparam     string
	Isintermediatereport bool
}

type Fsctype struct {
	Paramid             string
	Fsc                 string
	Noofbiterrorallowed int32
}

type Hkdetail struct {
	Hkdetailsid int32
	Sccname     string
	Username    sql.NullString
	Password    string
	Ipaddress   string
	Satname     string
	Stationid   string
	Chainname   string
	Path        string
	Framelength sql.NullInt32
	Startword   sql.NullInt32
	Noofwords   int32
}

type Incrementtype struct {
	Paramid    string
	Increment  int32
	Startvalue int32
	Endvalue   int32
	Tolerance  int32
}

type Parameterdetail struct {
	Paramid       string
	Satname       string
	Parametername string
	Parametertype ParameterdetailsParametertype
	Frametype     string
	Bitwise       bool
	Startword     int32
	Startbit      int32
	Noofbits      string
}

type Payload struct {
	Payloadid   int32
	Payloadname string
	Noofdevices int32
}

type Radixtype struct {
	Paramid                      string
	Radix                        int32
	Valuevalidationrequired      bool
	Differencevalidationrequired bool
	Upperlimitvalue              sql.NullInt32
	Lowerlimitvalue              sql.NullInt32
	Valuetolerance               sql.NullInt32
	Differencevalue              sql.NullInt32
	Differencetolerance          sql.NullInt32
}

type Remoteparameter struct {
	Paramid   int64
	Paramtype string
	Paramname string
	Maxlength int32
	Datatype  RemoteparametersDatatype
}

type Resultprofile struct {
	Profileid   int32
	Profilename string
	Noofresults int32
}

type Resultprofiledetail struct {
	Profileid      int32
	Resultid       int32
	Resultname     string
	Frametype      string
	Frameid        string
	Noofparameters int32
	Startline      int32
	Endline        int32
	Startword      int32
	Endword        int32
	Startpixel     int32
	Endpixel       int32
	Decimalorhex   bool
	Raworprocessed bool
	Ascordsc       bool
	Ismean         bool
	Issd           bool
	Stacklist      string
}

type Resultprofileparameter struct {
	Profileid int32
	Resultid  int32
	Paramid   string
}

type Sarvideodataprocessing struct {
	Processid            int32
	Startbyte            int32
	Payloadi1frameid     sql.NullInt32
	Payloadi2frameid     sql.NullInt32
	Payloadq1frameid     sql.NullInt32
	Payloadq2frameid     sql.NullInt32
	Polarizationpid      string
	Timingstatepid       string
	Baqpid               string
	Datawindowpid        string
	Chirpbwpid           string
	Sarmodepid           string
	Baqblocksize         int32
	Sarmodevalue         string
	Polvalue             string
	Timingstatetoexclude string
}

type Savedfile struct {
	Acquisitionid int32
	Frameid       int32
	Nooflines     int32
	Systemname    string
	Filepath      string
}

type Savedresult struct {
	Resultnumber    int32
	Uniqueid        []byte
	Acquisitionid   int32
	Systemname      string
	Frametype       string
	Frameidentifier sql.NullString
	Resultname      string
	Resultpath      sql.NullString
}

type Statustype struct {
	Paramid               string
	Bitvalue              string
	Interpretation        string
	Multiplevaluesallowed bool
}

type Testphase struct {
	Testphaseid int32
	Testphase   string
	Selected    bool
}

type User struct {
	Userid      int32
	Username    string
	Password    string
	Permissions string
}

type Videodataprocessing struct {
	Frameid                  int32
	Startbyte                int32
	Noofpixelsperline        int32
	Nooflinesperframe        int32
	Noofbitsperpixelpayload  int32
	Noofbitsperpixelcheckout int32
}

type Videofaultypixel struct {
	Frameid          int32
	Nooffaultypixels int32
	Pixelnumbers     string
}

type Videolimit struct {
	Frameid         int32
	Maxsd           float64
	Maxmean         float64
	Countdifference float64
}

type Videosubframe struct {
	Subframeid      int32
	Frameid         int32
	Subframetype    VideosubframesSubframetype
	Subframename    string
	Subframenumber  int32
	Startpixel      int32
	Endpixel        int32
	Pixelaccesstype VideosubframesPixelaccesstype
}
