// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
)

const changeDASIP = `-- name: ChangeDASIP :exec
Update ` + "`" + `DASDetails` + "`" + ` 
Set ` + "`" + `IPAddress` + "`" + ` = ? 
where ` + "`" + `DASName` + "`" + ` like ?
`

type ChangeDASIPParams struct {
	Ipaddress string
	Dasname   string
}

func (q *Queries) ChangeDASIP(ctx context.Context, arg ChangeDASIPParams) error {
	_, err := q.db.ExecContext(ctx, changeDASIP, arg.Ipaddress, arg.Dasname)
	return err
}

const changeRemark = `-- name: ChangeRemark :exec
Update ` + "`" + `Acquisitions` + "`" + ` Set ` + "`" + `Remark` + "`" + ` = ? 
where ` + "`" + `Date` + "`" + ` like ? and ` + "`" + `Time` + "`" + ` like ?
`

type ChangeRemarkParams struct {
	Remark string
	Date   string
	Time   string
}

func (q *Queries) ChangeRemark(ctx context.Context, arg ChangeRemarkParams) error {
	_, err := q.db.ExecContext(ctx, changeRemark, arg.Remark, arg.Date, arg.Time)
	return err
}

const checkIfConsolidatedSummaryExists = `-- name: CheckIfConsolidatedSummaryExists :one
Select Count(*) from ` + "`" + `ConsolidatedReport` + "`" + `
Where ` + "`" + `AcquisitionID` + "`" + ` = ? and ` + "`" + `SystemName` + "`" + ` = ? and ` + "`" + `FrameType` + "`" + ` = ?
`

type CheckIfConsolidatedSummaryExistsParams struct {
	Acquisitionid int32
	Systemname    string
	Frametype     string
}

func (q *Queries) CheckIfConsolidatedSummaryExists(ctx context.Context, arg CheckIfConsolidatedSummaryExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkIfConsolidatedSummaryExists, arg.Acquisitionid, arg.Systemname, arg.Frametype)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkIfSavedFileExists = `-- name: CheckIfSavedFileExists :one
SELECT COUNT(*) FROM ` + "`" + `SavedFiles` + "`" + ` WHERE 
` + "`" + `AcquisitionID` + "`" + ` = ? AND ` + "`" + `FrameID` + "`" + ` = ? 
AND ` + "`" + `SystemName` + "`" + ` = ?
`

type CheckIfSavedFileExistsParams struct {
	Acquisitionid int32
	Frameid       int32
	Systemname    string
}

func (q *Queries) CheckIfSavedFileExists(ctx context.Context, arg CheckIfSavedFileExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkIfSavedFileExists, arg.Acquisitionid, arg.Frameid, arg.Systemname)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkIfVideoConsolidatedSummaryExists = `-- name: CheckIfVideoConsolidatedSummaryExists :one
Select count(*) from ` + "`" + `ConsolidatedReport` + "`" + ` 
where ` + "`" + `AcquisitionID` + "`" + ` = ? and ` + "`" + `FrameType` + "`" + ` = ? 
and ` + "`" + `FrameID` + "`" + `=? and ` + "`" + `SystemName` + "`" + ` = ?
`

type CheckIfVideoConsolidatedSummaryExistsParams struct {
	Acquisitionid int32
	Frametype     string
	Frameid       sql.NullString
	Systemname    string
}

func (q *Queries) CheckIfVideoConsolidatedSummaryExists(ctx context.Context, arg CheckIfVideoConsolidatedSummaryExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkIfVideoConsolidatedSummaryExists,
		arg.Acquisitionid,
		arg.Frametype,
		arg.Frameid,
		arg.Systemname,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpticalSubTypes = `-- name: CountOpticalSubTypes :one
Select count(*) from ` + "`" + `VideoSubFrames` + "`" + ` 
where ` + "`" + `SubFrameType` + "`" + ` like ? and ` + "`" + `FrameID` + "`" + ` = ?
`

type CountOpticalSubTypesParams struct {
	Subframetype VideosubframesSubframetype
	Frameid      int32
}

func (q *Queries) CountOpticalSubTypes(ctx context.Context, arg CountOpticalSubTypesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpticalSubTypes, arg.Subframetype, arg.Frameid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAcquisition = `-- name: CreateAcquisition :execresult
INSERT INTO ` + "`" + `Acquisitions` + "`" + `
(` + "`" + `SystemName` + "`" + `, ` + "`" + `SatName` + "`" + `, ` + "`" + `TestPhase` + "`" + `, ` + "`" + `AcqMode` + "`" + `, ` + "`" + `Date` + "`" + `, ` + "`" + `Time` + "`" + `, ` + "`" + `ConfigName` + "`" + `, ` + "`" + `Remark` + "`" + `) 
VALUES ( ?, ?, ?, ?, ?, ?, ?, ? )
`

type CreateAcquisitionParams struct {
	Systemname string
	Satname    string
	Testphase  string
	Acqmode    string
	Date       string
	Time       string
	Configname string
	Remark     string
}

func (q *Queries) CreateAcquisition(ctx context.Context, arg CreateAcquisitionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAcquisition,
		arg.Systemname,
		arg.Satname,
		arg.Testphase,
		arg.Acqmode,
		arg.Date,
		arg.Time,
		arg.Configname,
		arg.Remark,
	)
}

const createOfflineResult = `-- name: CreateOfflineResult :exec
Insert into ` + "`" + `SavedResults` + "`" + ` 
(` + "`" + `UniqueID` + "`" + `,` + "`" + `AcquisitionID` + "`" + `, ` + "`" + `SystemName` + "`" + `, ` + "`" + `FrameType` + "`" + `, ` + "`" + `FrameIdentifier` + "`" + `, ` + "`" + `ResultName` + "`" + `, ` + "`" + `ResultPath` + "`" + `)
Values ( ? , ?, ?, ?, ?, ?, ?)
`

type CreateOfflineResultParams struct {
	Uniqueid        []byte
	Acquisitionid   int32
	Systemname      string
	Frametype       string
	Frameidentifier sql.NullString
	Resultname      string
	Resultpath      sql.NullString
}

func (q *Queries) CreateOfflineResult(ctx context.Context, arg CreateOfflineResultParams) error {
	_, err := q.db.ExecContext(ctx, createOfflineResult,
		arg.Uniqueid,
		arg.Acquisitionid,
		arg.Systemname,
		arg.Frametype,
		arg.Frameidentifier,
		arg.Resultname,
		arg.Resultpath,
	)
	return err
}

const createResultProfile = `-- name: CreateResultProfile :execresult
Insert into ` + "`" + `ResultProfiles` + "`" + ` 
(` + "`" + `ProfileName` + "`" + `, ` + "`" + `NoOfResults` + "`" + `) values (?,?)
`

type CreateResultProfileParams struct {
	Profilename string
	Noofresults int32
}

func (q *Queries) CreateResultProfile(ctx context.Context, arg CreateResultProfileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createResultProfile, arg.Profilename, arg.Noofresults)
}

const createResultProfileDetails = `-- name: CreateResultProfileDetails :exec
Insert into ` + "`" + `ResultProfileDetails` + "`" + ` 
(` + "`" + `ProfileID` + "`" + `,` + "`" + `ResultID` + "`" + `,` + "`" + `ResultName` + "`" + `,` + "`" + `FrameType` + "`" + `,` + "`" + `FrameID` + "`" + `,` + "`" + `NoOfParameters` + "`" + `,
 ` + "`" + `StartLine` + "`" + `,` + "`" + `EndLine` + "`" + `, ` + "`" + `StartWord` + "`" + `, ` + "`" + `EndWord` + "`" + `, ` + "`" + `StartPixel` + "`" + `, ` + "`" + `EndPixel` + "`" + ` ,
` + "`" + `DecimalOrHex` + "`" + `, ` + "`" + `RawOrProcessed` + "`" + `, ` + "`" + `AscOrDsc` + "`" + `, ` + "`" + `IsMean` + "`" + `, ` + "`" + `IsSD` + "`" + `, ` + "`" + `StackList` + "`" + ` )
values 
(?, ?, ?, ?, ?, ?,
?, ?, ?, ?, ?, ?,
?, ?, ?, ?, ?, ?)
`

type CreateResultProfileDetailsParams struct {
	Profileid      int32
	Resultid       int32
	Resultname     string
	Frametype      string
	Frameid        string
	Noofparameters int32
	Startline      int32
	Endline        int32
	Startword      int32
	Endword        int32
	Startpixel     int32
	Endpixel       int32
	Decimalorhex   bool
	Raworprocessed bool
	Ascordsc       bool
	Ismean         bool
	Issd           bool
	Stacklist      string
}

func (q *Queries) CreateResultProfileDetails(ctx context.Context, arg CreateResultProfileDetailsParams) error {
	_, err := q.db.ExecContext(ctx, createResultProfileDetails,
		arg.Profileid,
		arg.Resultid,
		arg.Resultname,
		arg.Frametype,
		arg.Frameid,
		arg.Noofparameters,
		arg.Startline,
		arg.Endline,
		arg.Startword,
		arg.Endword,
		arg.Startpixel,
		arg.Endpixel,
		arg.Decimalorhex,
		arg.Raworprocessed,
		arg.Ascordsc,
		arg.Ismean,
		arg.Issd,
		arg.Stacklist,
	)
	return err
}

const createResultProfileParameters = `-- name: CreateResultProfileParameters :exec
Insert into ` + "`" + `ResultProfileParameters` + "`" + ` 
(` + "`" + `ProfileID` + "`" + `, ` + "`" + `ResultID` + "`" + `, ` + "`" + `ParamID` + "`" + `)
values ( ? , ? , ?)
`

type CreateResultProfileParametersParams struct {
	Profileid int32
	Resultid  int32
	Paramid   string
}

func (q *Queries) CreateResultProfileParameters(ctx context.Context, arg CreateResultProfileParametersParams) error {
	_, err := q.db.ExecContext(ctx, createResultProfileParameters, arg.Profileid, arg.Resultid, arg.Paramid)
	return err
}

const createSavedFiles = `-- name: CreateSavedFiles :exec
Insert into ` + "`" + `SavedFiles` + "`" + ` 
(` + "`" + `AcquisitionID` + "`" + `, ` + "`" + `FrameID` + "`" + `, ` + "`" + `NoOfLines` + "`" + `, ` + "`" + `SystemName` + "`" + `, ` + "`" + `FilePath` + "`" + `)  
values ( ?, ?, ?, ?, ?)
`

type CreateSavedFilesParams struct {
	Acquisitionid int32
	Frameid       int32
	Nooflines     int32
	Systemname    string
	Filepath      string
}

func (q *Queries) CreateSavedFiles(ctx context.Context, arg CreateSavedFilesParams) error {
	_, err := q.db.ExecContext(ctx, createSavedFiles,
		arg.Acquisitionid,
		arg.Frameid,
		arg.Nooflines,
		arg.Systemname,
		arg.Filepath,
	)
	return err
}

const createTestPhase = `-- name: CreateTestPhase :exec
INSERT INTO ` + "`" + `TestPhases` + "`" + ` 
(` + "`" + `TestPhase` + "`" + `, ` + "`" + `Selected` + "`" + `) 
VALUES (?,1)
`

func (q *Queries) CreateTestPhase(ctx context.Context, testphase string) error {
	_, err := q.db.ExecContext(ctx, createTestPhase, testphase)
	return err
}

const deselectTestPhase = `-- name: DeselectTestPhase :exec
UPDATE ` + "`" + `TestPhases` + "`" + ` SET ` + "`" + `Selected` + "`" + ` = 0
`

func (q *Queries) DeselectTestPhase(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deselectTestPhase)
	return err
}

const filterSavedFiles = `-- name: FilterSavedFiles :many
SELECT acquisitionid, frameid, nooflines, systemname, filepath from ` + "`" + `SavedFiles` + "`" + ` WHERE 
` + "`" + `AcquisitionID` + "`" + ` = ? AND ` + "`" + `SystemName` + "`" + ` = ? 
AND FrameID IN (/*SLICE:frameids*/?) ORDER BY ` + "`" + `AcquisitionID` + "`" + ` DESC
`

type FilterSavedFilesParams struct {
	Acquisitionid int32
	Systemname    string
	Frameids      []int32
}

func (q *Queries) FilterSavedFiles(ctx context.Context, arg FilterSavedFilesParams) ([]Savedfile, error) {
	query := filterSavedFiles
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Acquisitionid)
	queryParams = append(queryParams, arg.Systemname)
	if len(arg.Frameids) > 0 {
		for _, v := range arg.Frameids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:frameids*/?", strings.Repeat(",?", len(arg.Frameids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:frameids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Savedfile
	for rows.Next() {
		var i Savedfile
		if err := rows.Scan(
			&i.Acquisitionid,
			&i.Frameid,
			&i.Nooflines,
			&i.Systemname,
			&i.Filepath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAcqID = `-- name: GetAcqID :one
Select ` + "`" + `AcqID` + "`" + ` from ` + "`" + `AcquisitionMode` + "`" + ` 
where ` + "`" + `AcqMode` + "`" + ` like ?
`

func (q *Queries) GetAcqID(ctx context.Context, acqmode string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getAcqID, acqmode)
	var acqid int32
	err := row.Scan(&acqid)
	return acqid, err
}

const getAcquiredFrameTypes = `-- name: GetAcquiredFrameTypes :many
Select ` + "`" + `FrameType` + "`" + ` from ` + "`" + `FrameTypes` + "`" + ` 
where ` + "`" + `ProcessedOrAcquired` + "`" + ` like '%acq%'
`

func (q *Queries) GetAcquiredFrameTypes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAcquiredFrameTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var frametype string
		if err := rows.Scan(&frametype); err != nil {
			return nil, err
		}
		items = append(items, frametype)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAcquiredSatelliteNames = `-- name: GetAcquiredSatelliteNames :many
SELECT Distinct ` + "`" + `SatName` + "`" + ` FROM ` + "`" + `Acquisitions` + "`" + `
`

func (q *Queries) GetAcquiredSatelliteNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAcquiredSatelliteNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var satname string
		if err := rows.Scan(&satname); err != nil {
			return nil, err
		}
		items = append(items, satname)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAcquiredTestPhases = `-- name: GetAcquiredTestPhases :many
SELECT ` + "`" + `TestPhase` + "`" + ` FROM ` + "`" + `Acquisitions` + "`" + `
Where ` + "`" + `SatName` + "`" + ` like ?
Order by AcquisitionID desc
`

func (q *Queries) GetAcquiredTestPhases(ctx context.Context, satname string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAcquiredTestPhases, satname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var testphase string
		if err := rows.Scan(&testphase); err != nil {
			return nil, err
		}
		items = append(items, testphase)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAcquisitionModes = `-- name: GetAcquisitionModes :many
Select ` + "`" + `AcqMode` + "`" + ` from ` + "`" + `AcquisitionMode` + "`" + `
where ` + "`" + `AcqType` + "`" + ` like ?
`

func (q *Queries) GetAcquisitionModes(ctx context.Context, acqtype AcquisitionmodeAcqtype) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAcquisitionModes, acqtype)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var acqmode string
		if err := rows.Scan(&acqmode); err != nil {
			return nil, err
		}
		items = append(items, acqmode)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAcquistionDetail = `-- name: GetAcquistionDetail :one
Select acquisitionid, systemname, satname, testphase, acqmode, date, time, configname, remark from ` + "`" + `Acquisitions` + "`" + ` 
WHERE ` + "`" + `AcquisitionID` + "`" + `= ? and ` + "`" + `SystemName` + "`" + ` = ?
`

type GetAcquistionDetailParams struct {
	Acquisitionid int32
	Systemname    string
}

func (q *Queries) GetAcquistionDetail(ctx context.Context, arg GetAcquistionDetailParams) (Acquisition, error) {
	row := q.db.QueryRowContext(ctx, getAcquistionDetail, arg.Acquisitionid, arg.Systemname)
	var i Acquisition
	err := row.Scan(
		&i.Acquisitionid,
		&i.Systemname,
		&i.Satname,
		&i.Testphase,
		&i.Acqmode,
		&i.Date,
		&i.Time,
		&i.Configname,
		&i.Remark,
	)
	return i, err
}

const getAcquistionDetailByTime = `-- name: GetAcquistionDetailByTime :one
Select acquisitionid, systemname, satname, testphase, acqmode, date, time, configname, remark from ` + "`" + `Acquisitions` + "`" + ` 
WHERE ` + "`" + `Date` + "`" + `= ? and ` + "`" + `Time` + "`" + ` = ?
`

type GetAcquistionDetailByTimeParams struct {
	Date string
	Time string
}

func (q *Queries) GetAcquistionDetailByTime(ctx context.Context, arg GetAcquistionDetailByTimeParams) (Acquisition, error) {
	row := q.db.QueryRowContext(ctx, getAcquistionDetailByTime, arg.Date, arg.Time)
	var i Acquisition
	err := row.Scan(
		&i.Acquisitionid,
		&i.Systemname,
		&i.Satname,
		&i.Testphase,
		&i.Acqmode,
		&i.Date,
		&i.Time,
		&i.Configname,
		&i.Remark,
	)
	return i, err
}

const getAcqusition = `-- name: GetAcqusition :one
Select acquisitionid, systemname, satname, testphase, acqmode, date, time, configname, remark from ` + "`" + `Acquisitions` + "`" + ` 
WHERE ` + "`" + `AcquisitionID` + "`" + ` = ? AND ` + "`" + `SystemName` + "`" + ` like ? 
AND ` + "`" + `TestPhase` + "`" + ` = ? Order by ` + "`" + `AcquisitionID` + "`" + ` desc
`

type GetAcqusitionParams struct {
	Acquisitionid int32
	Systemname    string
	Testphase     string
}

func (q *Queries) GetAcqusition(ctx context.Context, arg GetAcqusitionParams) (Acquisition, error) {
	row := q.db.QueryRowContext(ctx, getAcqusition, arg.Acquisitionid, arg.Systemname, arg.Testphase)
	var i Acquisition
	err := row.Scan(
		&i.Acquisitionid,
		&i.Systemname,
		&i.Satname,
		&i.Testphase,
		&i.Acqmode,
		&i.Date,
		&i.Time,
		&i.Configname,
		&i.Remark,
	)
	return i, err
}

const getAllAcquisitions = `-- name: GetAllAcquisitions :many
Select acquisitionid, systemname, satname, testphase, acqmode, date, time, configname, remark from ` + "`" + `Acquisitions` + "`" + ` 
Order by ` + "`" + `AcquisitionID` + "`" + ` desc
`

func (q *Queries) GetAllAcquisitions(ctx context.Context) ([]Acquisition, error) {
	rows, err := q.db.QueryContext(ctx, getAllAcquisitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Acquisition
	for rows.Next() {
		var i Acquisition
		if err := rows.Scan(
			&i.Acquisitionid,
			&i.Systemname,
			&i.Satname,
			&i.Testphase,
			&i.Acqmode,
			&i.Date,
			&i.Time,
			&i.Configname,
			&i.Remark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllConfigurations = `-- name: GetAllConfigurations :many
Select ` + "`" + `ConfigName` + "`" + ` from ` + "`" + `Configuration` + "`" + `
`

func (q *Queries) GetAllConfigurations(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllConfigurations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var configname string
		if err := rows.Scan(&configname); err != nil {
			return nil, err
		}
		items = append(items, configname)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDASDetails = `-- name: GetAllDASDetails :many
Select dasid, dasname, dastype, ipaddress, timeout from ` + "`" + `DASDetails` + "`" + `
`

func (q *Queries) GetAllDASDetails(ctx context.Context) ([]Dasdetail, error) {
	rows, err := q.db.QueryContext(ctx, getAllDASDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dasdetail
	for rows.Next() {
		var i Dasdetail
		if err := rows.Scan(
			&i.Dasid,
			&i.Dasname,
			&i.Dastype,
			&i.Ipaddress,
			&i.Timeout,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFrameIDs = `-- name: GetAllFrameIDs :many
Select ` + "`" + `FrameID` + "`" + ` from ` + "`" + `Frames` + "`" + `  
Order by ` + "`" + `FrameID` + "`" + ` asc
`

func (q *Queries) GetAllFrameIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getAllFrameIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var frameid int32
		if err := rows.Scan(&frameid); err != nil {
			return nil, err
		}
		items = append(items, frameid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllResultProfiles = `-- name: GetAllResultProfiles :many
Select ` + "`" + `ProfileName` + "`" + ` from ` + "`" + `ResultProfiles` + "`" + `
`

func (q *Queries) GetAllResultProfiles(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllResultProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var profilename string
		if err := rows.Scan(&profilename); err != nil {
			return nil, err
		}
		items = append(items, profilename)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnalogDetails = `-- name: GetAnalogDetails :one
Select paramid, equation, datatype, variablename, parameterids, valuevalidationrequired, differencevalidationrequired, lowerlimitvalue, upperlimitvalue, tolerancevalue, differencevalue, differencetolerance from ` + "`" + `AnalogType` + "`" + ` 
where ` + "`" + `ParamID` + "`" + ` = ?
`

func (q *Queries) GetAnalogDetails(ctx context.Context, paramid string) (Analogtype, error) {
	row := q.db.QueryRowContext(ctx, getAnalogDetails, paramid)
	var i Analogtype
	err := row.Scan(
		&i.Paramid,
		&i.Equation,
		&i.Datatype,
		&i.Variablename,
		&i.Parameterids,
		&i.Valuevalidationrequired,
		&i.Differencevalidationrequired,
		&i.Lowerlimitvalue,
		&i.Upperlimitvalue,
		&i.Tolerancevalue,
		&i.Differencevalue,
		&i.Differencetolerance,
	)
	return i, err
}

const getArchivableFrameTypes = `-- name: GetArchivableFrameTypes :many
Select ` + "`" + `FrameType` + "`" + ` from ` + "`" + `FrameTypes` + "`" + ` 
where ` + "`" + `ToBeArchived` + "`" + ` = 1
`

func (q *Queries) GetArchivableFrameTypes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getArchivableFrameTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var frametype string
		if err := rows.Scan(&frametype); err != nil {
			return nil, err
		}
		items = append(items, frametype)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuxFrameTypes = `-- name: GetAuxFrameTypes :many
Select ` + "`" + `FrameType` + "`" + ` from ` + "`" + `FrameTypes` + "`" + ` 
where ` + "`" + `Type` + "`" + ` like '%aux%'
`

func (q *Queries) GetAuxFrameTypes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAuxFrameTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var frametype string
		if err := rows.Scan(&frametype); err != nil {
			return nil, err
		}
		items = append(items, frametype)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBERLoggingDetails = `-- name: GetBERLoggingDetails :many
Select berid, acqmode, dasid, componentcode, frameid from ` + "`" + `BERLogging` + "`" + ` 
where ` + "`" + `AcqMode` + "`" + ` like ?
`

func (q *Queries) GetBERLoggingDetails(ctx context.Context, acqmode string) ([]Berlogging, error) {
	rows, err := q.db.QueryContext(ctx, getBERLoggingDetails, acqmode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Berlogging
	for rows.Next() {
		var i Berlogging
		if err := rows.Scan(
			&i.Berid,
			&i.Acqmode,
			&i.Dasid,
			&i.Componentcode,
			&i.Frameid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBitDetails = `-- name: GetBitDetails :many
Select bitid, paramid, wordno, validbits From ` + "`" + `BitDetails` + "`" + ` 
where ` + "`" + `ParamID` + "`" + ` like ?
`

func (q *Queries) GetBitDetails(ctx context.Context, paramid string) ([]Bitdetail, error) {
	rows, err := q.db.QueryContext(ctx, getBitDetails, paramid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bitdetail
	for rows.Next() {
		var i Bitdetail
		if err := rows.Scan(
			&i.Bitid,
			&i.Paramid,
			&i.Wordno,
			&i.Validbits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCRCDetails = `-- name: GetCRCDetails :one
Select paramid, startword, noofwords, crcpolynomial from ` + "`" + `CRCType` + "`" + ` 
where ` + "`" + `ParamID` + "`" + ` like ?
`

func (q *Queries) GetCRCDetails(ctx context.Context, paramid string) (Crctype, error) {
	row := q.db.QueryRowContext(ctx, getCRCDetails, paramid)
	var i Crctype
	err := row.Scan(
		&i.Paramid,
		&i.Startword,
		&i.Noofwords,
		&i.Crcpolynomial,
	)
	return i, err
}

const getChainDetails = `-- name: GetChainDetails :many
Select daspathid, acqmode, chainnumber, dasid, dpunumber, dataframeid, headerframeid, trailerframeid from ` + "`" + `DASPath` + "`" + `
where ` + "`" + `AcqMode` + "`" + ` = ?
`

func (q *Queries) GetChainDetails(ctx context.Context, acqmode string) ([]Daspath, error) {
	rows, err := q.db.QueryContext(ctx, getChainDetails, acqmode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Daspath
	for rows.Next() {
		var i Daspath
		if err := rows.Scan(
			&i.Daspathid,
			&i.Acqmode,
			&i.Chainnumber,
			&i.Dasid,
			&i.Dpunumber,
			&i.Dataframeid,
			&i.Headerframeid,
			&i.Trailerframeid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConfigNameForAcqMode = `-- name: GetConfigNameForAcqMode :many
Select ` + "`" + `ConfigName` + "`" + ` from ` + "`" + `Configuration` + "`" + ` 
where ` + "`" + `AcqMode` + "`" + ` like ?
`

func (q *Queries) GetConfigNameForAcqMode(ctx context.Context, acqmode string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getConfigNameForAcqMode, acqmode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var configname string
		if err := rows.Scan(&configname); err != nil {
			return nil, err
		}
		items = append(items, configname)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConsolidatedReportFrameIdentifer = `-- name: GetConsolidatedReportFrameIdentifer :one
Select consolidatedreportid, acquisitionid, systemname, frametype, frameid, auxdatacorrect, maxmean, meanofmean, maxsd, meansd, rmssd, path, noofframes from ` + "`" + `ConsolidatedReport` + "`" + ` 
where ` + "`" + `AcquisitionID` + "`" + ` = ? and ` + "`" + `FrameType` + "`" + ` like ? and 
` + "`" + `FrameID` + "`" + ` like ? and ` + "`" + `SystemName` + "`" + `= ?
`

type GetConsolidatedReportFrameIdentiferParams struct {
	Acquisitionid int32
	Frametype     string
	Frameid       sql.NullString
	Systemname    string
}

func (q *Queries) GetConsolidatedReportFrameIdentifer(ctx context.Context, arg GetConsolidatedReportFrameIdentiferParams) (Consolidatedreport, error) {
	row := q.db.QueryRowContext(ctx, getConsolidatedReportFrameIdentifer,
		arg.Acquisitionid,
		arg.Frametype,
		arg.Frameid,
		arg.Systemname,
	)
	var i Consolidatedreport
	err := row.Scan(
		&i.Consolidatedreportid,
		&i.Acquisitionid,
		&i.Systemname,
		&i.Frametype,
		&i.Frameid,
		&i.Auxdatacorrect,
		&i.Maxmean,
		&i.Meanofmean,
		&i.Maxsd,
		&i.Meansd,
		&i.Rmssd,
		&i.Path,
		&i.Noofframes,
	)
	return i, err
}

const getConsolidatedReports = `-- name: GetConsolidatedReports :many
Select consolidatedreportid, acquisitionid, systemname, frametype, frameid, auxdatacorrect, maxmean, meanofmean, maxsd, meansd, rmssd, path, noofframes from ` + "`" + `ConsolidatedReport` + "`" + ` 
Where ` + "`" + `AcquisitionID` + "`" + ` = ? and ` + "`" + `SystemName` + "`" + ` = ?
`

type GetConsolidatedReportsParams struct {
	Acquisitionid int32
	Systemname    string
}

func (q *Queries) GetConsolidatedReports(ctx context.Context, arg GetConsolidatedReportsParams) ([]Consolidatedreport, error) {
	rows, err := q.db.QueryContext(ctx, getConsolidatedReports, arg.Acquisitionid, arg.Systemname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Consolidatedreport
	for rows.Next() {
		var i Consolidatedreport
		if err := rows.Scan(
			&i.Consolidatedreportid,
			&i.Acquisitionid,
			&i.Systemname,
			&i.Frametype,
			&i.Frameid,
			&i.Auxdatacorrect,
			&i.Maxmean,
			&i.Meanofmean,
			&i.Maxsd,
			&i.Meansd,
			&i.Rmssd,
			&i.Path,
			&i.Noofframes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDASComponentDetails = `-- name: GetDASComponentDetails :one
Select componentid, componentname, parentcompname, componentcode, totallengthinwords, configlengthinwords, excludedwords, startword, startbit, noofbits, value, enabled from ` + "`" + `DASComponentDetails` + "`" + ` 
where ` + "`" + `ComponentID` + "`" + ` = ?
`

func (q *Queries) GetDASComponentDetails(ctx context.Context, componentid int32) (Dascomponentdetail, error) {
	row := q.db.QueryRowContext(ctx, getDASComponentDetails, componentid)
	var i Dascomponentdetail
	err := row.Scan(
		&i.Componentid,
		&i.Componentname,
		&i.Parentcompname,
		&i.Componentcode,
		&i.Totallengthinwords,
		&i.Configlengthinwords,
		&i.Excludedwords,
		&i.Startword,
		&i.Startbit,
		&i.Noofbits,
		&i.Value,
		&i.Enabled,
	)
	return i, err
}

const getDASComponentDetailsByCompCode = `-- name: GetDASComponentDetailsByCompCode :one
Select componentid, componentname, parentcompname, componentcode, totallengthinwords, configlengthinwords, excludedwords, startword, startbit, noofbits, value, enabled from ` + "`" + `DASComponentDetails` + "`" + ` 
where ` + "`" + `ComponentCode` + "`" + ` = ? and ` + "`" + `Enabled` + "`" + ` = 1
`

func (q *Queries) GetDASComponentDetailsByCompCode(ctx context.Context, componentcode string) (Dascomponentdetail, error) {
	row := q.db.QueryRowContext(ctx, getDASComponentDetailsByCompCode, componentcode)
	var i Dascomponentdetail
	err := row.Scan(
		&i.Componentid,
		&i.Componentname,
		&i.Parentcompname,
		&i.Componentcode,
		&i.Totallengthinwords,
		&i.Configlengthinwords,
		&i.Excludedwords,
		&i.Startword,
		&i.Startbit,
		&i.Noofbits,
		&i.Value,
		&i.Enabled,
	)
	return i, err
}

const getDASConfigurations = `-- name: GetDASConfigurations :many
SELECT id, acquisitionmode, dasid, componentcode, setparameters, verifyparameters, executionorder, delayafterms
FROM DASConfigurations
WHERE AcquisitionMode = ? AND DASID = ?
ORDER BY ExecutionOrder ASC
`

type GetDASConfigurationsParams struct {
	Acquisitionmode string
	Dasid           int32
}

func (q *Queries) GetDASConfigurations(ctx context.Context, arg GetDASConfigurationsParams) ([]Dasconfiguration, error) {
	rows, err := q.db.QueryContext(ctx, getDASConfigurations, arg.Acquisitionmode, arg.Dasid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dasconfiguration
	for rows.Next() {
		var i Dasconfiguration
		if err := rows.Scan(
			&i.ID,
			&i.Acquisitionmode,
			&i.Dasid,
			&i.Componentcode,
			&i.Setparameters,
			&i.Verifyparameters,
			&i.Executionorder,
			&i.Delayafterms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDASDetails = `-- name: GetDASDetails :one
Select dasid, dasname, dastype, ipaddress, timeout from ` + "`" + `DASDetails` + "`" + ` 
where ` + "`" + `DASID` + "`" + ` = ?
`

func (q *Queries) GetDASDetails(ctx context.Context, dasid int32) (Dasdetail, error) {
	row := q.db.QueryRowContext(ctx, getDASDetails, dasid)
	var i Dasdetail
	err := row.Scan(
		&i.Dasid,
		&i.Dasname,
		&i.Dastype,
		&i.Ipaddress,
		&i.Timeout,
	)
	return i, err
}

const getDASID = `-- name: GetDASID :one
Select ` + "`" + `DASID` + "`" + ` from ` + "`" + `DASDetails` + "`" + ` 
where ` + "`" + `DASName` + "`" + ` = ?
`

func (q *Queries) GetDASID(ctx context.Context, dasname string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getDASID, dasname)
	var dasid int32
	err := row.Scan(&dasid)
	return dasid, err
}

const getDASSystemsByAcquisitionMode = `-- name: GetDASSystemsByAcquisitionMode :many
SELECT DISTINCT d.dasid, d.dasname, d.dastype, d.ipaddress, d.timeout
FROM ` + "`" + `DASDetails` + "`" + ` d
JOIN ` + "`" + `DASPath` + "`" + ` p ON d.` + "`" + `DASID` + "`" + ` = p.` + "`" + `DASID` + "`" + `
WHERE p.` + "`" + `AcqMode` + "`" + ` = ?
`

func (q *Queries) GetDASSystemsByAcquisitionMode(ctx context.Context, acqmode string) ([]Dasdetail, error) {
	rows, err := q.db.QueryContext(ctx, getDASSystemsByAcquisitionMode, acqmode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dasdetail
	for rows.Next() {
		var i Dasdetail
		if err := rows.Scan(
			&i.Dasid,
			&i.Dasname,
			&i.Dastype,
			&i.Ipaddress,
			&i.Timeout,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDependentDASComponents = `-- name: GetDependentDASComponents :many
Select componentid, componentname, parentcompname, componentcode, totallengthinwords, configlengthinwords, excludedwords, startword, startbit, noofbits, value, enabled from ` + "`" + `DASComponentDetails` + "`" + ` 
where  ` + "`" + `ParentCompName` + "`" + ` IS NOT NULL
`

func (q *Queries) GetDependentDASComponents(ctx context.Context) ([]Dascomponentdetail, error) {
	rows, err := q.db.QueryContext(ctx, getDependentDASComponents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dascomponentdetail
	for rows.Next() {
		var i Dascomponentdetail
		if err := rows.Scan(
			&i.Componentid,
			&i.Componentname,
			&i.Parentcompname,
			&i.Componentcode,
			&i.Totallengthinwords,
			&i.Configlengthinwords,
			&i.Excludedwords,
			&i.Startword,
			&i.Startbit,
			&i.Noofbits,
			&i.Value,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctDASID = `-- name: GetDistinctDASID :many
Select Distinct ` + "`" + `DASID` + "`" + ` from ` + "`" + `DASPath` + "`" + ` 
where ` + "`" + `AcqMode` + "`" + ` = ?
`

func (q *Queries) GetDistinctDASID(ctx context.Context, acqmode string) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctDASID, acqmode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var dasid int32
		if err := rows.Scan(&dasid); err != nil {
			return nil, err
		}
		items = append(items, dasid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctDASIDAndDPUNumber = `-- name: GetDistinctDASIDAndDPUNumber :many
Select Distinct ` + "`" + `DASID` + "`" + `, ` + "`" + `DPUNumber` + "`" + ` from ` + "`" + `DASPath` + "`" + `
`

type GetDistinctDASIDAndDPUNumberRow struct {
	Dasid     int32
	Dpunumber int32
}

func (q *Queries) GetDistinctDASIDAndDPUNumber(ctx context.Context) ([]GetDistinctDASIDAndDPUNumberRow, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctDASIDAndDPUNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDistinctDASIDAndDPUNumberRow
	for rows.Next() {
		var i GetDistinctDASIDAndDPUNumberRow
		if err := rows.Scan(&i.Dasid, &i.Dpunumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnabledDASComponents = `-- name: GetEnabledDASComponents :many
Select componentid, componentname, parentcompname, componentcode, totallengthinwords, configlengthinwords, excludedwords, startword, startbit, noofbits, value, enabled from ` + "`" + `DASComponentDetails` + "`" + `
where ` + "`" + `Enabled` + "`" + ` = 1
`

func (q *Queries) GetEnabledDASComponents(ctx context.Context) ([]Dascomponentdetail, error) {
	rows, err := q.db.QueryContext(ctx, getEnabledDASComponents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dascomponentdetail
	for rows.Next() {
		var i Dascomponentdetail
		if err := rows.Scan(
			&i.Componentid,
			&i.Componentname,
			&i.Parentcompname,
			&i.Componentcode,
			&i.Totallengthinwords,
			&i.Configlengthinwords,
			&i.Excludedwords,
			&i.Startword,
			&i.Startbit,
			&i.Noofbits,
			&i.Value,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFSCDetails = `-- name: GetFSCDetails :one
Select paramid, fsc, noofbiterrorallowed from ` + "`" + `FSCType` + "`" + ` 
where ` + "`" + `ParamID` + "`" + ` like ?
`

func (q *Queries) GetFSCDetails(ctx context.Context, paramid string) (Fsctype, error) {
	row := q.db.QueryRowContext(ctx, getFSCDetails, paramid)
	var i Fsctype
	err := row.Scan(&i.Paramid, &i.Fsc, &i.Noofbiterrorallowed)
	return i, err
}

const getFSCParamID = `-- name: GetFSCParamID :one
Select ` + "`" + `ParamID` + "`" + ` from ` + "`" + `ParameterDetails` + "`" + ` 
where ` + "`" + `FrameType` + "`" + ` like ? and ` + "`" + `ParameterType` + "`" + ` like 'FSC'
`

func (q *Queries) GetFSCParamID(ctx context.Context, frametype string) (string, error) {
	row := q.db.QueryRowContext(ctx, getFSCParamID, frametype)
	var paramid string
	err := row.Scan(&paramid)
	return paramid, err
}

const getFrameDetails = `-- name: GetFrameDetails :one
Select frameid, frametype, frameidentifier, framefilename, framelength, identifyingvalue from ` + "`" + `Frames` + "`" + `
where ` + "`" + `FrameID` + "`" + ` like ?
`

func (q *Queries) GetFrameDetails(ctx context.Context, frameid int32) (Frame, error) {
	row := q.db.QueryRowContext(ctx, getFrameDetails, frameid)
	var i Frame
	err := row.Scan(
		&i.Frameid,
		&i.Frametype,
		&i.Frameidentifier,
		&i.Framefilename,
		&i.Framelength,
		&i.Identifyingvalue,
	)
	return i, err
}

const getFrameID = `-- name: GetFrameID :one
Select ` + "`" + `FrameID` + "`" + ` from ` + "`" + `Frames` + "`" + ` 
where ` + "`" + `FrameType` + "`" + ` = ? and ` + "`" + `FrameIdentifier` + "`" + ` = ?
`

type GetFrameIDParams struct {
	Frametype       string
	Frameidentifier string
}

func (q *Queries) GetFrameID(ctx context.Context, arg GetFrameIDParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getFrameID, arg.Frametype, arg.Frameidentifier)
	var frameid int32
	err := row.Scan(&frameid)
	return frameid, err
}

const getFrameIDForFrameType = `-- name: GetFrameIDForFrameType :many
Select ` + "`" + `FrameID` + "`" + ` from ` + "`" + `Frames` + "`" + `
Where ` + "`" + `FrameType` + "`" + ` like ?
`

func (q *Queries) GetFrameIDForFrameType(ctx context.Context, frametype string) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getFrameIDForFrameType, frametype)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var frameid int32
		if err := rows.Scan(&frameid); err != nil {
			return nil, err
		}
		items = append(items, frameid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFrameIDsForDownload = `-- name: GetFrameIDsForDownload :many
Select ` + "`" + `FrameID` + "`" + ` from ` + "`" + `DataDownloadPermissions` + "`" + ` 
where ` + "`" + `UserID` + "`" + ` = ?
`

func (q *Queries) GetFrameIDsForDownload(ctx context.Context, userid int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getFrameIDsForDownload, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var frameid int32
		if err := rows.Scan(&frameid); err != nil {
			return nil, err
		}
		items = append(items, frameid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFrameTypeDetails = `-- name: GetFrameTypeDetails :one
Select frametypeid, satname, frametype, type, processedoracquired, tobewritten, tobearchived, identifyingparam, framelengthparam, isintermediatereport from ` + "`" + `FrameTypes` + "`" + ` 
where ` + "`" + `FrameType` + "`" + ` = ?
`

func (q *Queries) GetFrameTypeDetails(ctx context.Context, frametype string) (Frametype, error) {
	row := q.db.QueryRowContext(ctx, getFrameTypeDetails, frametype)
	var i Frametype
	err := row.Scan(
		&i.Frametypeid,
		&i.Satname,
		&i.Frametype,
		&i.Type,
		&i.Processedoracquired,
		&i.Tobewritten,
		&i.Tobearchived,
		&i.Identifyingparam,
		&i.Framelengthparam,
		&i.Isintermediatereport,
	)
	return i, err
}

const getFrameTypeFrameIdentifiers = `-- name: GetFrameTypeFrameIdentifiers :many
Select frameid, frametype, frameidentifier, framefilename, framelength, identifyingvalue from ` + "`" + `Frames` + "`" + ` 
where ` + "`" + `FrameType` + "`" + ` like ? order by ` + "`" + `FrameID` + "`" + ` asc
`

func (q *Queries) GetFrameTypeFrameIdentifiers(ctx context.Context, frametype string) ([]Frame, error) {
	rows, err := q.db.QueryContext(ctx, getFrameTypeFrameIdentifiers, frametype)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Frame
	for rows.Next() {
		var i Frame
		if err := rows.Scan(
			&i.Frameid,
			&i.Frametype,
			&i.Frameidentifier,
			&i.Framefilename,
			&i.Framelength,
			&i.Identifyingvalue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFrameTypeParamterDetails = `-- name: GetFrameTypeParamterDetails :many
Select paramid, satname, parametername, parametertype, frametype, bitwise, startword, startbit, noofbits from ` + "`" + `ParameterDetails` + "`" + `
where ` + "`" + `FrameType` + "`" + ` like ? order by ` + "`" + `StartWord` + "`" + `, ` + "`" + `StartBit` + "`" + ` Asc
`

func (q *Queries) GetFrameTypeParamterDetails(ctx context.Context, frametype string) ([]Parameterdetail, error) {
	rows, err := q.db.QueryContext(ctx, getFrameTypeParamterDetails, frametype)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Parameterdetail
	for rows.Next() {
		var i Parameterdetail
		if err := rows.Scan(
			&i.Paramid,
			&i.Satname,
			&i.Parametername,
			&i.Parametertype,
			&i.Frametype,
			&i.Bitwise,
			&i.Startword,
			&i.Startbit,
			&i.Noofbits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFrameTypes = `-- name: GetFrameTypes :many
Select ` + "`" + `FrameType` + "`" + ` from ` + "`" + `FrameTypes` + "`" + `
`

func (q *Queries) GetFrameTypes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getFrameTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var frametype string
		if err := rows.Scan(&frametype); err != nil {
			return nil, err
		}
		items = append(items, frametype)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHKDetails = `-- name: GetHKDetails :many
Select hkdetailsid, sccname, username, password, ipaddress, satname, stationid, chainname, path, framelength, startword, noofwords from HKDetails
`

func (q *Queries) GetHKDetails(ctx context.Context) ([]Hkdetail, error) {
	rows, err := q.db.QueryContext(ctx, getHKDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hkdetail
	for rows.Next() {
		var i Hkdetail
		if err := rows.Scan(
			&i.Hkdetailsid,
			&i.Sccname,
			&i.Username,
			&i.Password,
			&i.Ipaddress,
			&i.Satname,
			&i.Stationid,
			&i.Chainname,
			&i.Path,
			&i.Framelength,
			&i.Startword,
			&i.Noofwords,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncrementDetails = `-- name: GetIncrementDetails :one
Select paramid, increment, startvalue, endvalue, tolerance from ` + "`" + `IncrementType` + "`" + `
where ` + "`" + `ParamID` + "`" + ` like ?
`

func (q *Queries) GetIncrementDetails(ctx context.Context, paramid string) (Incrementtype, error) {
	row := q.db.QueryRowContext(ctx, getIncrementDetails, paramid)
	var i Incrementtype
	err := row.Scan(
		&i.Paramid,
		&i.Increment,
		&i.Startvalue,
		&i.Endvalue,
		&i.Tolerance,
	)
	return i, err
}

const getIntermediateFrames = `-- name: GetIntermediateFrames :many
SELECT ` + "`" + `FrameType` + "`" + ` FROM ` + "`" + `FrameTypes` + "`" + ` 
where ` + "`" + `isIntermediateReport` + "`" + ` = 1 and ` + "`" + `Type` + "`" + ` like ?
`

func (q *Queries) GetIntermediateFrames(ctx context.Context, type_ FrametypesType) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getIntermediateFrames, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var frametype string
		if err := rows.Scan(&frametype); err != nil {
			return nil, err
		}
		items = append(items, frametype)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxResultNumber = `-- name: GetMaxResultNumber :many
Select ` + "`" + `ResultNumber` + "`" + ` from ` + "`" + `SavedResults` + "`" + ` 
Order by ` + "`" + `ResultNumber` + "`" + ` desc
`

func (q *Queries) GetMaxResultNumber(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getMaxResultNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var resultnumber int32
		if err := rows.Scan(&resultnumber); err != nil {
			return nil, err
		}
		items = append(items, resultnumber)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrowaveFrameTypes = `-- name: GetMicrowaveFrameTypes :many
Select ` + "`" + `FrameType` + "`" + ` from ` + "`" + `FrameTypes` + "`" + ` 
where ` + "`" + `Type` + "`" + ` like '%microwave%'
`

func (q *Queries) GetMicrowaveFrameTypes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getMicrowaveFrameTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var frametype string
		if err := rows.Scan(&frametype); err != nil {
			return nil, err
		}
		items = append(items, frametype)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrowavePolarization = `-- name: GetMicrowavePolarization :one
SELECT ` + "`" + `PolarizationPID` + "`" + ` FROM ` + "`" + `SARVideoDataProcessing` + "`" + `
`

func (q *Queries) GetMicrowavePolarization(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getMicrowavePolarization)
	var polarizationpid string
	err := row.Scan(&polarizationpid)
	return polarizationpid, err
}

const getMicrowaveProcessingDetails = `-- name: GetMicrowaveProcessingDetails :one
Select processid, startbyte, payloadi1frameid, payloadi2frameid, payloadq1frameid, payloadq2frameid, polarizationpid, timingstatepid, baqpid, datawindowpid, chirpbwpid, sarmodepid, baqblocksize, sarmodevalue, polvalue, timingstatetoexclude from ` + "`" + `SARVideoDataProcessing` + "`" + ` 
where ` + "`" + `ProcessID` + "`" + ` = ?
`

func (q *Queries) GetMicrowaveProcessingDetails(ctx context.Context, processid int32) (Sarvideodataprocessing, error) {
	row := q.db.QueryRowContext(ctx, getMicrowaveProcessingDetails, processid)
	var i Sarvideodataprocessing
	err := row.Scan(
		&i.Processid,
		&i.Startbyte,
		&i.Payloadi1frameid,
		&i.Payloadi2frameid,
		&i.Payloadq1frameid,
		&i.Payloadq2frameid,
		&i.Polarizationpid,
		&i.Timingstatepid,
		&i.Baqpid,
		&i.Datawindowpid,
		&i.Chirpbwpid,
		&i.Sarmodepid,
		&i.Baqblocksize,
		&i.Sarmodevalue,
		&i.Polvalue,
		&i.Timingstatetoexclude,
	)
	return i, err
}

const getMicrowaveProcessingID = `-- name: GetMicrowaveProcessingID :many
SELECT ` + "`" + `ProcessID` + "`" + ` FROM ` + "`" + `SARVideoDataProcessing` + "`" + `
`

func (q *Queries) GetMicrowaveProcessingID(ctx context.Context) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getMicrowaveProcessingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var processid int32
		if err := rows.Scan(&processid); err != nil {
			return nil, err
		}
		items = append(items, processid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMicrowaveTimingState = `-- name: GetMicrowaveTimingState :one
SELECT ` + "`" + `TimingStatePID` + "`" + ` FROM ` + "`" + `SARVideoDataProcessing` + "`" + `
`

func (q *Queries) GetMicrowaveTimingState(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getMicrowaveTimingState)
	var timingstatepid string
	err := row.Scan(&timingstatepid)
	return timingstatepid, err
}

const getOfflineProcessingResults = `-- name: GetOfflineProcessingResults :many
Select acquisitionid, systemname, satname, testphase, acqmode, date, time, configname, remark from ` + "`" + `Acquisitions` + "`" + ` 
where ` + "`" + `SatName` + "`" + ` like ? and ` + "`" + `TestPhase` + "`" + ` like ?
and ` + "`" + `ConfigName` + "`" + ` like ? and ` + "`" + `Date` + "`" + ` like ? 
and ` + "`" + `Time` + "`" + ` like ? and ` + "`" + `AcqMode` + "`" + ` like ?
and ` + "`" + `Remark` + "`" + ` like ? Order by ` + "`" + `AcquisitionID` + "`" + ` desc
`

type GetOfflineProcessingResultsParams struct {
	Satname    string
	Testphase  string
	Configname string
	Date       string
	Time       string
	Acqmode    string
	Remark     string
}

func (q *Queries) GetOfflineProcessingResults(ctx context.Context, arg GetOfflineProcessingResultsParams) ([]Acquisition, error) {
	rows, err := q.db.QueryContext(ctx, getOfflineProcessingResults,
		arg.Satname,
		arg.Testphase,
		arg.Configname,
		arg.Date,
		arg.Time,
		arg.Acqmode,
		arg.Remark,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Acquisition
	for rows.Next() {
		var i Acquisition
		if err := rows.Scan(
			&i.Acquisitionid,
			&i.Systemname,
			&i.Satname,
			&i.Testphase,
			&i.Acqmode,
			&i.Date,
			&i.Time,
			&i.Configname,
			&i.Remark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpticalFaultyPixels = `-- name: GetOpticalFaultyPixels :one
Select frameid, nooffaultypixels, pixelnumbers from ` + "`" + `VideoFaultyPixels` + "`" + ` 
where ` + "`" + `FrameID` + "`" + ` = ?
`

func (q *Queries) GetOpticalFaultyPixels(ctx context.Context, frameid int32) (Videofaultypixel, error) {
	row := q.db.QueryRowContext(ctx, getOpticalFaultyPixels, frameid)
	var i Videofaultypixel
	err := row.Scan(&i.Frameid, &i.Nooffaultypixels, &i.Pixelnumbers)
	return i, err
}

const getOpticalFrameTypes = `-- name: GetOpticalFrameTypes :many
Select ` + "`" + `FrameType` + "`" + ` from ` + "`" + `FrameTypes` + "`" + ` 
where ` + "`" + `Type` + "`" + ` like '%optical%'
`

func (q *Queries) GetOpticalFrameTypes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getOpticalFrameTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var frametype string
		if err := rows.Scan(&frametype); err != nil {
			return nil, err
		}
		items = append(items, frametype)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpticalLimitDetails = `-- name: GetOpticalLimitDetails :one
Select frameid, maxsd, maxmean, countdifference from ` + "`" + `VideoLimits` + "`" + ` 
where ` + "`" + `FrameID` + "`" + ` = ?
`

func (q *Queries) GetOpticalLimitDetails(ctx context.Context, frameid int32) (Videolimit, error) {
	row := q.db.QueryRowContext(ctx, getOpticalLimitDetails, frameid)
	var i Videolimit
	err := row.Scan(
		&i.Frameid,
		&i.Maxsd,
		&i.Maxmean,
		&i.Countdifference,
	)
	return i, err
}

const getOpticalSubFrameDetails = `-- name: GetOpticalSubFrameDetails :one
Select subframeid, frameid, subframetype, subframename, subframenumber, startpixel, endpixel, pixelaccesstype from ` + "`" + `VideoSubFrames` + "`" + ` 
where ` + "`" + `SubFrameType` + "`" + ` like ? and ` + "`" + `SubFrameNumber` + "`" + ` = ? 
and ` + "`" + `FrameID` + "`" + ` = ?
`

type GetOpticalSubFrameDetailsParams struct {
	Subframetype   VideosubframesSubframetype
	Subframenumber int32
	Frameid        int32
}

func (q *Queries) GetOpticalSubFrameDetails(ctx context.Context, arg GetOpticalSubFrameDetailsParams) (Videosubframe, error) {
	row := q.db.QueryRowContext(ctx, getOpticalSubFrameDetails, arg.Subframetype, arg.Subframenumber, arg.Frameid)
	var i Videosubframe
	err := row.Scan(
		&i.Subframeid,
		&i.Frameid,
		&i.Subframetype,
		&i.Subframename,
		&i.Subframenumber,
		&i.Startpixel,
		&i.Endpixel,
		&i.Pixelaccesstype,
	)
	return i, err
}

const getOpticalSubFrameNumber = `-- name: GetOpticalSubFrameNumber :one
Select subframeid, frameid, subframetype, subframename, subframenumber, startpixel, endpixel, pixelaccesstype from ` + "`" + `VideoSubFrames` + "`" + ` 
where ` + "`" + `SubFrameType` + "`" + ` like ? and ` + "`" + `FrameID` + "`" + ` = ? 
and ` + "`" + `SubFrameName` + "`" + ` like ?
`

type GetOpticalSubFrameNumberParams struct {
	Subframetype VideosubframesSubframetype
	Frameid      int32
	Subframename string
}

func (q *Queries) GetOpticalSubFrameNumber(ctx context.Context, arg GetOpticalSubFrameNumberParams) (Videosubframe, error) {
	row := q.db.QueryRowContext(ctx, getOpticalSubFrameNumber, arg.Subframetype, arg.Frameid, arg.Subframename)
	var i Videosubframe
	err := row.Scan(
		&i.Subframeid,
		&i.Frameid,
		&i.Subframetype,
		&i.Subframename,
		&i.Subframenumber,
		&i.Startpixel,
		&i.Endpixel,
		&i.Pixelaccesstype,
	)
	return i, err
}

const getOpticalSubFrames = `-- name: GetOpticalSubFrames :many
Select subframeid, frameid, subframetype, subframename, subframenumber, startpixel, endpixel, pixelaccesstype from ` + "`" + `VideoSubFrames` + "`" + ` 
where ` + "`" + `SubFrameType` + "`" + ` like ? and ` + "`" + `FrameID` + "`" + ` = ?  
Order By ` + "`" + `SubFrameNumber` + "`" + `
`

type GetOpticalSubFramesParams struct {
	Subframetype VideosubframesSubframetype
	Frameid      int32
}

func (q *Queries) GetOpticalSubFrames(ctx context.Context, arg GetOpticalSubFramesParams) ([]Videosubframe, error) {
	rows, err := q.db.QueryContext(ctx, getOpticalSubFrames, arg.Subframetype, arg.Frameid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Videosubframe
	for rows.Next() {
		var i Videosubframe
		if err := rows.Scan(
			&i.Subframeid,
			&i.Frameid,
			&i.Subframetype,
			&i.Subframename,
			&i.Subframenumber,
			&i.Startpixel,
			&i.Endpixel,
			&i.Pixelaccesstype,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParamID = `-- name: GetParamID :one
Select ` + "`" + `ParamID` + "`" + ` from ` + "`" + `ParameterDetails` + "`" + ` 
where ` + "`" + `FrameType` + "`" + ` like ? and ` + "`" + `ParameterName` + "`" + ` like ?
`

type GetParamIDParams struct {
	Frametype     string
	Parametername string
}

func (q *Queries) GetParamID(ctx context.Context, arg GetParamIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getParamID, arg.Frametype, arg.Parametername)
	var paramid string
	err := row.Scan(&paramid)
	return paramid, err
}

const getParameterDetails = `-- name: GetParameterDetails :one
Select paramid, satname, parametername, parametertype, frametype, bitwise, startword, startbit, noofbits from ` + "`" + `ParameterDetails` + "`" + ` 
where ` + "`" + `ParamID` + "`" + ` like ?
`

func (q *Queries) GetParameterDetails(ctx context.Context, paramid string) (Parameterdetail, error) {
	row := q.db.QueryRowContext(ctx, getParameterDetails, paramid)
	var i Parameterdetail
	err := row.Scan(
		&i.Paramid,
		&i.Satname,
		&i.Parametername,
		&i.Parametertype,
		&i.Frametype,
		&i.Bitwise,
		&i.Startword,
		&i.Startbit,
		&i.Noofbits,
	)
	return i, err
}

const getPayloads = `-- name: GetPayloads :many
SELECT ` + "`" + `PayloadName` + "`" + ` FROM ` + "`" + `Payloads` + "`" + `
`

func (q *Queries) GetPayloads(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getPayloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var payloadname string
		if err := rows.Scan(&payloadname); err != nil {
			return nil, err
		}
		items = append(items, payloadname)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRadixDetails = `-- name: GetRadixDetails :one
Select paramid, radix, valuevalidationrequired, differencevalidationrequired, upperlimitvalue, lowerlimitvalue, valuetolerance, differencevalue, differencetolerance from ` + "`" + `RadixType` + "`" + ` 
where ` + "`" + `ParamID` + "`" + ` like ?
`

func (q *Queries) GetRadixDetails(ctx context.Context, paramid string) (Radixtype, error) {
	row := q.db.QueryRowContext(ctx, getRadixDetails, paramid)
	var i Radixtype
	err := row.Scan(
		&i.Paramid,
		&i.Radix,
		&i.Valuevalidationrequired,
		&i.Differencevalidationrequired,
		&i.Upperlimitvalue,
		&i.Lowerlimitvalue,
		&i.Valuetolerance,
		&i.Differencevalue,
		&i.Differencetolerance,
	)
	return i, err
}

const getRemoteParameterDetails = `-- name: GetRemoteParameterDetails :one
Select paramid, paramtype, paramname, maxlength, datatype from ` + "`" + `RemoteParameters` + "`" + ` 
WHERE ` + "`" + `ParamID` + "`" + ` = ?
`

func (q *Queries) GetRemoteParameterDetails(ctx context.Context, paramid int64) (Remoteparameter, error) {
	row := q.db.QueryRowContext(ctx, getRemoteParameterDetails, paramid)
	var i Remoteparameter
	err := row.Scan(
		&i.Paramid,
		&i.Paramtype,
		&i.Paramname,
		&i.Maxlength,
		&i.Datatype,
	)
	return i, err
}

const getResultProfileDetails = `-- name: GetResultProfileDetails :many
Select profileid, resultid, resultname, frametype, frameid, noofparameters, startline, endline, startword, endword, startpixel, endpixel, decimalorhex, raworprocessed, ascordsc, ismean, issd, stacklist from ` + "`" + `ResultProfileDetails` + "`" + `
where ` + "`" + `ProfileID` + "`" + ` = ?
`

func (q *Queries) GetResultProfileDetails(ctx context.Context, profileid int32) ([]Resultprofiledetail, error) {
	rows, err := q.db.QueryContext(ctx, getResultProfileDetails, profileid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resultprofiledetail
	for rows.Next() {
		var i Resultprofiledetail
		if err := rows.Scan(
			&i.Profileid,
			&i.Resultid,
			&i.Resultname,
			&i.Frametype,
			&i.Frameid,
			&i.Noofparameters,
			&i.Startline,
			&i.Endline,
			&i.Startword,
			&i.Endword,
			&i.Startpixel,
			&i.Endpixel,
			&i.Decimalorhex,
			&i.Raworprocessed,
			&i.Ascordsc,
			&i.Ismean,
			&i.Issd,
			&i.Stacklist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResultProfileID = `-- name: GetResultProfileID :one
Select ` + "`" + `ProfileID` + "`" + ` from ` + "`" + `ResultProfiles` + "`" + ` 
where ` + "`" + `ProfileName` + "`" + ` like ?
`

func (q *Queries) GetResultProfileID(ctx context.Context, profilename string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getResultProfileID, profilename)
	var profileid int32
	err := row.Scan(&profileid)
	return profileid, err
}

const getResultProfileParameters = `-- name: GetResultProfileParameters :many
Select profileid, resultid, paramid from ` + "`" + `ResultProfileParameters` + "`" + ` 
where ` + "`" + `ProfileID` + "`" + ` = ? and ` + "`" + `ResultID` + "`" + ` = ?
`

type GetResultProfileParametersParams struct {
	Profileid int32
	Resultid  int32
}

func (q *Queries) GetResultProfileParameters(ctx context.Context, arg GetResultProfileParametersParams) ([]Resultprofileparameter, error) {
	rows, err := q.db.QueryContext(ctx, getResultProfileParameters, arg.Profileid, arg.Resultid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resultprofileparameter
	for rows.Next() {
		var i Resultprofileparameter
		if err := rows.Scan(&i.Profileid, &i.Resultid, &i.Paramid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSavedFilesForAcquisition = `-- name: GetSavedFilesForAcquisition :many
Select acquisitionid, frameid, nooflines, systemname, filepath from ` + "`" + `SavedFiles` + "`" + ` 
where ` + "`" + `AcquisitionID` + "`" + ` = ? and ` + "`" + `SystemName` + "`" + ` = ?
`

type GetSavedFilesForAcquisitionParams struct {
	Acquisitionid int32
	Systemname    string
}

func (q *Queries) GetSavedFilesForAcquisition(ctx context.Context, arg GetSavedFilesForAcquisitionParams) ([]Savedfile, error) {
	rows, err := q.db.QueryContext(ctx, getSavedFilesForAcquisition, arg.Acquisitionid, arg.Systemname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Savedfile
	for rows.Next() {
		var i Savedfile
		if err := rows.Scan(
			&i.Acquisitionid,
			&i.Frameid,
			&i.Nooflines,
			&i.Systemname,
			&i.Filepath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSavedFilesForFrameIDs = `-- name: GetSavedFilesForFrameIDs :many
SELECT acquisitionid, frameid, nooflines, systemname, filepath from ` + "`" + `SavedFiles` + "`" + ` 
WHERE ` + "`" + `FrameID` + "`" + ` IN (/*SLICE:frameids*/?) ORDER BY ` + "`" + `AcquisitionID` + "`" + ` DESC
`

func (q *Queries) GetSavedFilesForFrameIDs(ctx context.Context, frameids []int32) ([]Savedfile, error) {
	query := getSavedFilesForFrameIDs
	var queryParams []interface{}
	if len(frameids) > 0 {
		for _, v := range frameids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:frameids*/?", strings.Repeat(",?", len(frameids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:frameids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Savedfile
	for rows.Next() {
		var i Savedfile
		if err := rows.Scan(
			&i.Acquisitionid,
			&i.Frameid,
			&i.Nooflines,
			&i.Systemname,
			&i.Filepath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSavedResults = `-- name: GetSavedResults :one
Select resultnumber, uniqueid, acquisitionid, systemname, frametype, frameidentifier, resultname, resultpath from ` + "`" + `SavedResults` + "`" + ` 
Where ` + "`" + `ResultNumber` + "`" + ` = ? and ` + "`" + `SystemName` + "`" + `= ?
`

type GetSavedResultsParams struct {
	Resultnumber int32
	Systemname   string
}

func (q *Queries) GetSavedResults(ctx context.Context, arg GetSavedResultsParams) (Savedresult, error) {
	row := q.db.QueryRowContext(ctx, getSavedResults, arg.Resultnumber, arg.Systemname)
	var i Savedresult
	err := row.Scan(
		&i.Resultnumber,
		&i.Uniqueid,
		&i.Acquisitionid,
		&i.Systemname,
		&i.Frametype,
		&i.Frameidentifier,
		&i.Resultname,
		&i.Resultpath,
	)
	return i, err
}

const getSavedResultsForAcquisition = `-- name: GetSavedResultsForAcquisition :many
Select resultnumber, uniqueid, acquisitionid, systemname, frametype, frameidentifier, resultname, resultpath from ` + "`" + `SavedResults` + "`" + `
Where ` + "`" + `AcquisitionID` + "`" + ` = ? and ` + "`" + `SystemName` + "`" + ` = ?
`

type GetSavedResultsForAcquisitionParams struct {
	Acquisitionid int32
	Systemname    string
}

func (q *Queries) GetSavedResultsForAcquisition(ctx context.Context, arg GetSavedResultsForAcquisitionParams) ([]Savedresult, error) {
	rows, err := q.db.QueryContext(ctx, getSavedResultsForAcquisition, arg.Acquisitionid, arg.Systemname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Savedresult
	for rows.Next() {
		var i Savedresult
		if err := rows.Scan(
			&i.Resultnumber,
			&i.Uniqueid,
			&i.Acquisitionid,
			&i.Systemname,
			&i.Frametype,
			&i.Frameidentifier,
			&i.Resultname,
			&i.Resultpath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSelectedTestPhase = `-- name: GetSelectedTestPhase :one
SELECT ` + "`" + `TestPhase` + "`" + ` FROM ` + "`" + `TestPhases` + "`" + ` 
where ` + "`" + `Selected` + "`" + ` = 1
`

func (q *Queries) GetSelectedTestPhase(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getSelectedTestPhase)
	var testphase string
	err := row.Scan(&testphase)
	return testphase, err
}

const getStatusDetails = `-- name: GetStatusDetails :many
Select paramid, bitvalue, interpretation, multiplevaluesallowed from ` + "`" + `StatusType` + "`" + ` 
where ` + "`" + `ParamID` + "`" + ` like ?
`

func (q *Queries) GetStatusDetails(ctx context.Context, paramid string) ([]Statustype, error) {
	rows, err := q.db.QueryContext(ctx, getStatusDetails, paramid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Statustype
	for rows.Next() {
		var i Statustype
		if err := rows.Scan(
			&i.Paramid,
			&i.Bitvalue,
			&i.Interpretation,
			&i.Multiplevaluesallowed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTestPhases = `-- name: GetTestPhases :many
SELECT ` + "`" + `TestPhase` + "`" + ` FROM ` + "`" + `TestPhases` + "`" + `
`

func (q *Queries) GetTestPhases(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTestPhases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var testphase string
		if err := rows.Scan(&testphase); err != nil {
			return nil, err
		}
		items = append(items, testphase)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTypeOfFrame = `-- name: GetTypeOfFrame :one
SELECT ` + "`" + `Type` + "`" + ` FROM ` + "`" + `FrameTypes` + "`" + ` 
where ` + "`" + `FrameType` + "`" + ` like ?
`

func (q *Queries) GetTypeOfFrame(ctx context.Context, frametype string) (FrametypesType, error) {
	row := q.db.QueryRowContext(ctx, getTypeOfFrame, frametype)
	var type_ FrametypesType
	err := row.Scan(&type_)
	return type_, err
}

const getUniqueDASForBER = `-- name: GetUniqueDASForBER :many
Select Distinct ` + "`" + `DASID` + "`" + ` from ` + "`" + `BERLogging` + "`" + ` 
where ` + "`" + `AcqMode` + "`" + ` = ?
`

func (q *Queries) GetUniqueDASForBER(ctx context.Context, acqmode string) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getUniqueDASForBER, acqmode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var dasid int32
		if err := rows.Scan(&dasid); err != nil {
			return nil, err
		}
		items = append(items, dasid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDetails = `-- name: GetUserDetails :one
SELECT userid, username, password, permissions FROM ` + "`" + `Users` + "`" + ` WHERE ` + "`" + `UserName` + "`" + ` = ?
`

func (q *Queries) GetUserDetails(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserDetails, username)
	var i User
	err := row.Scan(
		&i.Userid,
		&i.Username,
		&i.Password,
		&i.Permissions,
	)
	return i, err
}

const getVideoDataDetails = `-- name: GetVideoDataDetails :one
Select frameid, startbyte, noofpixelsperline, nooflinesperframe, noofbitsperpixelpayload, noofbitsperpixelcheckout from ` + "`" + `VideoDataProcessing` + "`" + `
where ` + "`" + `FrameID` + "`" + ` = ?
`

func (q *Queries) GetVideoDataDetails(ctx context.Context, frameid int32) (Videodataprocessing, error) {
	row := q.db.QueryRowContext(ctx, getVideoDataDetails, frameid)
	var i Videodataprocessing
	err := row.Scan(
		&i.Frameid,
		&i.Startbyte,
		&i.Noofpixelsperline,
		&i.Nooflinesperframe,
		&i.Noofbitsperpixelpayload,
		&i.Noofbitsperpixelcheckout,
	)
	return i, err
}

const getWritableFrameTypes = `-- name: GetWritableFrameTypes :many
Select ` + "`" + `FrameType` + "`" + ` from ` + "`" + `FrameTypes` + "`" + ` 
where ` + "`" + `ToBeWritten` + "`" + ` = 1
`

func (q *Queries) GetWritableFrameTypes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getWritableFrameTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var frametype string
		if err := rows.Scan(&frametype); err != nil {
			return nil, err
		}
		items = append(items, frametype)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuxConsolidatedReport = `-- name: InsertAuxConsolidatedReport :exec
Insert into ` + "`" + `ConsolidatedReport` + "`" + `
(` + "`" + `AcquisitionID` + "`" + `, ` + "`" + `SystemName` + "`" + `, ` + "`" + `FrameType` + "`" + `, ` + "`" + `AuxDataCorrect` + "`" + `, ` + "`" + `NoOfFrames` + "`" + `)  
values (?, ?, ?, ?, ?)
`

type InsertAuxConsolidatedReportParams struct {
	Acquisitionid  int32
	Systemname     string
	Frametype      string
	Auxdatacorrect sql.NullString
	Noofframes     string
}

func (q *Queries) InsertAuxConsolidatedReport(ctx context.Context, arg InsertAuxConsolidatedReportParams) error {
	_, err := q.db.ExecContext(ctx, insertAuxConsolidatedReport,
		arg.Acquisitionid,
		arg.Systemname,
		arg.Frametype,
		arg.Auxdatacorrect,
		arg.Noofframes,
	)
	return err
}

const insertVideoConsolidatedReport = `-- name: InsertVideoConsolidatedReport :exec
Insert into ` + "`" + `ConsolidatedReport` + "`" + `
(` + "`" + `AcquisitionID` + "`" + `, ` + "`" + `SystemName` + "`" + `, ` + "`" + `FrameType` + "`" + `,` + "`" + `FrameID` + "`" + `, ` + "`" + `MaxMean` + "`" + `, 
` + "`" + `MeanOfMean` + "`" + `, ` + "`" + `MaxSD` + "`" + `, ` + "`" + `MeanSD` + "`" + `, ` + "`" + `RMSSD` + "`" + `, ` + "`" + `Path` + "`" + `, ` + "`" + `NoOfFrames` + "`" + `)
values (?, ?, ?, ?, ?, 
?, ?, ?, ?, ?, ?)
`

type InsertVideoConsolidatedReportParams struct {
	Acquisitionid int32
	Systemname    string
	Frametype     string
	Frameid       sql.NullString
	Maxmean       sql.NullFloat64
	Meanofmean    sql.NullFloat64
	Maxsd         sql.NullFloat64
	Meansd        sql.NullFloat64
	Rmssd         sql.NullFloat64
	Path          sql.NullString
	Noofframes    string
}

func (q *Queries) InsertVideoConsolidatedReport(ctx context.Context, arg InsertVideoConsolidatedReportParams) error {
	_, err := q.db.ExecContext(ctx, insertVideoConsolidatedReport,
		arg.Acquisitionid,
		arg.Systemname,
		arg.Frametype,
		arg.Frameid,
		arg.Maxmean,
		arg.Meanofmean,
		arg.Maxsd,
		arg.Meansd,
		arg.Rmssd,
		arg.Path,
		arg.Noofframes,
	)
	return err
}

const removeResultProfile = `-- name: RemoveResultProfile :exec
Delete from ` + "`" + `ResultProfiles` + "`" + ` 
where ` + "`" + `ProfileID` + "`" + ` = ?
`

func (q *Queries) RemoveResultProfile(ctx context.Context, profileid int32) error {
	_, err := q.db.ExecContext(ctx, removeResultProfile, profileid)
	return err
}

const removeResultProfileDetails = `-- name: RemoveResultProfileDetails :exec
Delete from ` + "`" + `ResultProfileDetails` + "`" + `
where ` + "`" + `ProfileID` + "`" + ` = ?
`

func (q *Queries) RemoveResultProfileDetails(ctx context.Context, profileid int32) error {
	_, err := q.db.ExecContext(ctx, removeResultProfileDetails, profileid)
	return err
}

const removeResultProfileParameters = `-- name: RemoveResultProfileParameters :exec
Delete from ` + "`" + `ResultProfileParameters` + "`" + ` 
where ` + "`" + `ProfileID` + "`" + ` = ?
`

func (q *Queries) RemoveResultProfileParameters(ctx context.Context, profileid int32) error {
	_, err := q.db.ExecContext(ctx, removeResultProfileParameters, profileid)
	return err
}

const selectTestPhase = `-- name: SelectTestPhase :exec
UPDATE ` + "`" + `TestPhases` + "`" + ` SET ` + "`" + `Selected` + "`" + ` = 1 
WHERE ` + "`" + `TestPhase` + "`" + ` like ?
`

func (q *Queries) SelectTestPhase(ctx context.Context, testphase string) error {
	_, err := q.db.ExecContext(ctx, selectTestPhase, testphase)
	return err
}

const updateAuxConsolidatedReport = `-- name: UpdateAuxConsolidatedReport :exec
Update ` + "`" + `ConsolidatedReport` + "`" + ` Set
` + "`" + `AuxDataCorrect` + "`" + ` = ?, ` + "`" + `NoOfFrames` + "`" + ` = ?
Where ` + "`" + `AcquisitionID` + "`" + ` = ? and ` + "`" + `SystemName` + "`" + ` = ? and ` + "`" + `FrameType` + "`" + ` = ?
`

type UpdateAuxConsolidatedReportParams struct {
	Auxdatacorrect sql.NullString
	Noofframes     string
	Acquisitionid  int32
	Systemname     string
	Frametype      string
}

func (q *Queries) UpdateAuxConsolidatedReport(ctx context.Context, arg UpdateAuxConsolidatedReportParams) error {
	_, err := q.db.ExecContext(ctx, updateAuxConsolidatedReport,
		arg.Auxdatacorrect,
		arg.Noofframes,
		arg.Acquisitionid,
		arg.Systemname,
		arg.Frametype,
	)
	return err
}

const updateVideoConsolidatedReport = `-- name: UpdateVideoConsolidatedReport :exec
UPDATE ConsolidatedReport SET 
` + "`" + `MaxMean` + "`" + ` = ?,` + "`" + `MeanOfMean` + "`" + `=?,` + "`" + `MaxSD` + "`" + `=?,` + "`" + `MeanSD` + "`" + `=?,` + "`" + `RMSSD` + "`" + `=?,
` + "`" + `Path` + "`" + `=?,` + "`" + `NoOfFrames` + "`" + `=? 
WHERE ` + "`" + `AcquisitionID` + "`" + ` = ? and ` + "`" + `FrameType` + "`" + ` = ? 
and ` + "`" + `FrameID` + "`" + ` = ? and ` + "`" + `SystemName` + "`" + ` = ?
`

type UpdateVideoConsolidatedReportParams struct {
	Maxmean       sql.NullFloat64
	Meanofmean    sql.NullFloat64
	Maxsd         sql.NullFloat64
	Meansd        sql.NullFloat64
	Rmssd         sql.NullFloat64
	Path          sql.NullString
	Noofframes    string
	Acquisitionid int32
	Frametype     string
	Frameid       sql.NullString
	Systemname    string
}

func (q *Queries) UpdateVideoConsolidatedReport(ctx context.Context, arg UpdateVideoConsolidatedReportParams) error {
	_, err := q.db.ExecContext(ctx, updateVideoConsolidatedReport,
		arg.Maxmean,
		arg.Meanofmean,
		arg.Maxsd,
		arg.Meansd,
		arg.Rmssd,
		arg.Path,
		arg.Noofframes,
		arg.Acquisitionid,
		arg.Frametype,
		arg.Frameid,
		arg.Systemname,
	)
	return err
}
